/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.DataProvider;
import DAO.NhanVien_DAO;
import DTO.NhanVien_DTO;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nguye
 */
public class NhanVien_GUI extends javax.swing.JFrame {
    private TrangChu_GUI trangChu_GUI = null;
    private String maNV = null;
    
    private ArrayList<NhanVien_DTO> l_nhanviens = null;
    /**
     * Creates new form NhanVien_GUI
     */
    public NhanVien_GUI(TrangChu_GUI trangChu_GUI, String maNV) {
        this.trangChu_GUI = trangChu_GUI;
        this.maNV = maNV;
        initComponents();
        
        this.setLocationRelativeTo(null);
        this.setTitle("Quản lý nhân viên");
        this.setVisible(true);
        
        this.title.setHorizontalAlignment(SwingConstants.CENTER);
        this.title.setHorizontalTextPosition(SwingConstants.CENTER);
        
        ImageIcon imageIcon = new ImageIcon("src/Pictures/imgNhanVien.jpg");
        Image image = imageIcon.getImage().getScaledInstance(centerHome.getWidth(), centerHome.getHeight(), Image.SCALE_SMOOTH);
        centerHome.setIcon(new ImageIcon(image));
        
        this.setItemCbb_ChucVu();
       
        this.loadTableNhanVien();
        
        Picker_ngaySinh.setDate(Date.from(Instant.now()));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Text_maNV = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Text_tenNV = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Text_cmnd = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Text_sdt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Cbb_chucVu = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        radioNu = new javax.swing.JRadioButton();
        radioNam = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        Text_DiaChi = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        Text_Email = new javax.swing.JTextField();
        title = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_nhanVien = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        radioTheoTen = new javax.swing.JRadioButton();
        radioTheoSdt = new javax.swing.JRadioButton();
        Text_search = new javax.swing.JTextField();
        radioTheoCMND = new javax.swing.JRadioButton();
        centerHome = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnThemMoi = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        btn_TaiKhoanNV = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("THÔNG TIN NHÂN VIÊN"));

        Text_maNV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text_maNV.setFocusAccelerator('1');

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Mã nhân viên:");

        Text_tenNV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text_tenNV.setFocusAccelerator('2');

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("CMND:");

        Text_cmnd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text_cmnd.setFocusAccelerator('4');
        Text_cmnd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Text_cmndMouseClicked(evt);
            }
        });
        Text_cmnd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Text_cmndKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Tên nhân viên:");

        Text_sdt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text_sdt.setFocusAccelerator('3');
        Text_sdt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Text_sdtMouseClicked(evt);
            }
        });
        Text_sdt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Text_sdtKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Số điện thoai:");

        Cbb_chucVu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Chức vụ:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Giới tính:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Ngày sinh:");

        radioNu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radioNu.setText("Nữ");
        radioNu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                radioNuMousePressed(evt);
            }
        });

        radioNam.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radioNam.setSelected(true);
        radioNam.setText("Nam");
        radioNam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                radioNamMousePressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Địa chỉ:");

        Text_DiaChi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text_DiaChi.setFocusAccelerator('6');

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Email:");

        Text_Email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text_Email.setFocusAccelerator('5');

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Text_maNV, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Text_sdt))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Text_tenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Text_cmnd, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Cbb_chucVu, 0, 271, Short.MAX_VALUE)
                            .addComponent(Text_DiaChi)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(radioNam)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radioNu)
                        .addGap(137, 137, 137)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Text_Email)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12)
                                .addComponent(Text_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(radioNam)
                                .addComponent(radioNu)))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Text_cmnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel2))
                            .addComponent(Text_maNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(Text_tenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Text_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(Text_DiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(Cbb_chucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(0, 102, 204));
        title.setText("QUẢN LÝ NHÂN VIÊN");
        title.setToolTipText("");

        Table_nhanVien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Table_nhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        Table_nhanVien.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        Table_nhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_nhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table_nhanVien);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("TÌM KIẾM"));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Tìm kiếm:");

        radioTheoTen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radioTheoTen.setSelected(true);
        radioTheoTen.setText("Theo tên");
        radioTheoTen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                radioTheoTenMousePressed(evt);
            }
        });

        radioTheoSdt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radioTheoSdt.setText("Theo sdt");
        radioTheoSdt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                radioTheoSdtMousePressed(evt);
            }
        });

        Text_search.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Text_search.setFocusAccelerator('7');
        Text_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Text_searchKeyReleased(evt);
            }
        });

        radioTheoCMND.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radioTheoCMND.setText("Theo CMND");
        radioTheoCMND.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                radioTheoCMNDMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(radioTheoTen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radioTheoSdt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radioTheoCMND)
                        .addGap(0, 51, Short.MAX_VALUE))
                    .addComponent(Text_search))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioTheoSdt)
                    .addComponent(radioTheoTen)
                    .addComponent(radioTheoCMND))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Text_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("THAO TÁC"));

        btnThemMoi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnThemMoi.setText("Thêm mới");
        btnThemMoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemMoiMouseClicked(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnXoa.setText("Xoá");
        btnXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXoaMouseClicked(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSuaMouseClicked(evt);
            }
        });

        btnLamMoi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLamMoi.setText("Làm mới");
        btnLamMoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLamMoiMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThemMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLamMoi, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btn_TaiKhoanNV.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_TaiKhoanNV.setText("Tài khoản nhân viên");
        btn_TaiKhoanNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_TaiKhoanNVMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(centerHome, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(title)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_TaiKhoanNV, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_TaiKhoanNV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(centerHome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void addColumnTableNhanVien(){
        DefaultTableModel tableNhanVien = (DefaultTableModel)Table_nhanVien.getModel();
        tableNhanVien.setColumnIdentifiers(new String[]{
            "Mã nhân viên", "Tên nhân viên", "Ngày sinh", "Giới tính", "Email", "Số điện thoại", "CMND", "Địa chỉ", "Chức vụ"
        });
        
        var getColumnTable = Table_nhanVien.getColumnModel();
        
        getColumnTable.getColumn(0).setPreferredWidth(120);
        getColumnTable.getColumn(1).setPreferredWidth(200);
        getColumnTable.getColumn(2).setPreferredWidth(130);
        getColumnTable.getColumn(3).setPreferredWidth(100);
        getColumnTable.getColumn(4).setPreferredWidth(200);
        getColumnTable.getColumn(5).setPreferredWidth(120);
        getColumnTable.getColumn(6).setPreferredWidth(120);
        getColumnTable.getColumn(7).setPreferredWidth(200);
        getColumnTable.getColumn(8).setPreferredWidth(120);
       
        Table_nhanVien.getTableHeader().setFont( new Font( "Arial" , Font.BOLD, 15 ));
    }
    
    private void loadTableNhanVien(){
        this.addColumnTableNhanVien();
        
        DefaultTableModel tableNhanVien = (DefaultTableModel)Table_nhanVien.getModel();
       
        tableNhanVien.setRowCount(0);
        this.l_nhanviens = NhanVien_DAO.getListNhanVien();
    
        for(NhanVien_DTO nhanvien : this.l_nhanviens){
            tableNhanVien.addRow(new String[]{
                nhanvien.getMaNV(),
                nhanvien.getTenNhanVien(),
                new SimpleDateFormat("dd/MM/yyyy").format(nhanvien.getNgaySinh()),
                nhanvien.getGioiTinh(),
                nhanvien.getEmail(),
                nhanvien.getSdt(),
                nhanvien.getCmnd(),
                nhanvien.getDiaChi(),
                nhanvien.getChucVu()
            });
        }
        
    }
    
    private void setItemCbb_ChucVu(){
       
        String[] chucVu = new String[]{"Nhân viên", "Quản lý"};
        for(String item : chucVu){
            Cbb_chucVu.addItem(item);
        }
    }
    
    
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this, "Bạn muốn quay lại trang chính ?", "Thông báo", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.OK_OPTION){
            this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            this.trangChu_GUI.setEnabled(true);
            return;
        }
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }//GEN-LAST:event_formWindowClosing

    private void btn_TaiKhoanNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_TaiKhoanNVMouseClicked
        // TODO add your handling code here:
        new TaiKhoan_GUI(this, this.maNV);
        this.setVisible(false);
    }//GEN-LAST:event_btn_TaiKhoanNVMouseClicked

    private void radioTheoSdtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioTheoSdtMousePressed
        // TODO add your handling code here:
        radioTheoTen.setSelected(false);
        radioTheoCMND.setSelected(false);
    }//GEN-LAST:event_radioTheoSdtMousePressed

    private void radioTheoTenMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioTheoTenMousePressed
        // TODO add your handling code here:
        radioTheoSdt.setSelected(false);
        radioTheoCMND.setSelected(false);
    }//GEN-LAST:event_radioTheoTenMousePressed

    private void radioTheoCMNDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioTheoCMNDMousePressed
        // TODO add your handling code here:
        radioTheoTen.setSelected(false);
        radioTheoSdt.setSelected(false);
    }//GEN-LAST:event_radioTheoCMNDMousePressed

    private void radioNamMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioNamMousePressed
        // TODO add your handling code here:
        radioNu.setSelected(false);
    }//GEN-LAST:event_radioNamMousePressed

    private void radioNuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radioNuMousePressed
        // TODO add your handling code here:
        radioNam.setSelected(false);
    }//GEN-LAST:event_radioNuMousePressed

    private void Table_nhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_nhanVienMouseClicked
        // TODO add your handling code here:
        if(Table_nhanVien.getSelectedRowCount() == 1){
            ArrayList<String> valuesColumn = new ArrayList<String>();
            int numRow = Table_nhanVien.getSelectedRow();
            for(int i = 0; i < Table_nhanVien.getColumnCount(); i++){
                String value = Table_nhanVien.getValueAt(numRow, i).toString();
                valuesColumn.add(value);
            }

            Text_maNV.setText(valuesColumn.get(0));
            Text_maNV.setFocusable(false);
            Text_tenNV.setText(valuesColumn.get(1));
            try {
                Picker_ngaySinh.setDate(new SimpleDateFormat("dd/MM/yyyy").parse(valuesColumn.get(2)));
            } catch (ParseException ex) {}

            if(valuesColumn.get(3).equals("Nam")){
                radioNam.setSelected(true);
                radioNu.setSelected(false);
            }
            else{
                radioNu.setSelected(true);
                radioNam.setSelected(false);
            }

            Text_Email.setText(valuesColumn.get(4));
            Text_sdt.setText(valuesColumn.get(5));
            Text_cmnd.setText(valuesColumn.get(6));
            Text_DiaChi.setText(valuesColumn.get(7));
            Cbb_chucVu.setSelectedItem(valuesColumn.get(8));
           
        }
    }//GEN-LAST:event_Table_nhanVienMouseClicked

    private void btnLamMoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLamMoiMouseClicked
        // TODO add your handling code here:
        Text_DiaChi.setText("");
        Text_Email.setText("");
        Text_cmnd.setText("");
        Text_maNV.setText("");
        Text_maNV.setFocusable(true);
        Text_sdt.setText("");
        Text_search.setText("");
        Text_tenNV.setText("");
        Picker_ngaySinh.setDate(Date.from(Instant.now()));
        Cbb_chucVu.setSelectedItem("Nhân viên");
        radioNam.setSelected(true);
        radioNu.setSelected(false);
        radioTheoTen.setSelected(true);
        radioTheoCMND.setSelected(false);
        radioTheoSdt.setSelected(false);
        btnThemMoi.requestFocus();
        this.loadTableNhanVien();
    }//GEN-LAST:event_btnLamMoiMouseClicked

    private ArrayList<JTextField> l_TextF(){
        ArrayList<JTextField> l_Text = new ArrayList<JTextField>();
        l_Text.add(Text_DiaChi);
        l_Text.add(Text_Email);
        l_Text.add(Text_cmnd);
        l_Text.add(Text_maNV);
        l_Text.add(Text_sdt);
        l_Text.add(Text_tenNV);
        return l_Text;
    }
    
    private void btnThemMoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMoiMouseClicked
        // TODO add your handling code here:
        ArrayList<JTextField> l_TextFields = this.l_TextF();
        for(JTextField textF : l_TextFields){
            if(textF.getText().equals("") || Picker_ngaySinh.getDate().equals("")){
                JOptionPane.showConfirmDialog(this, "Hãy nhập đầy đủ dữ liệu", "Thông báo", JOptionPane.CLOSED_OPTION, JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
        
        String MaNV = Text_maNV.getText();
        String hoTen = Text_tenNV.getText();
        String gioiTinh = radioNam.isSelected() ? radioNam.getText() : radioNu.getText();
        String email = Text_Email.getText();
        String sdt = Text_sdt.getText();
        String cmnd = Text_cmnd.getText();
        String diaChi = Text_DiaChi.getText();
        String chucVu = Cbb_chucVu.getSelectedItem().toString();
        String ngaySinh = new SimpleDateFormat("yyyy-MM-dd").format(Picker_ngaySinh.getDate());
        
        int resultCheck = NhanVien_DAO.checkExistNhanVien(email, sdt, cmnd);
   
        if(resultCheck == 0){
            int result = NhanVien_DAO.addNewNhanVien(MaNV, hoTen, ngaySinh, gioiTinh, email, sdt, cmnd, diaChi, chucVu);
            if(result >= 1){
                JOptionPane.showConfirmDialog(this, "Thêm mới nhân viên thành công !!!", "Thông báo", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE);
                this.loadTableNhanVien();
                return;
            }
            
            JOptionPane.showConfirmDialog(this, "Có vẻ như lỗi thêm nhân viên !!!", "Thông báo", JOptionPane.CLOSED_OPTION, JOptionPane.ERROR_MESSAGE);
            return;
        }
        else{
            if(resultCheck == -1){
                JOptionPane.showConfirmDialog(this, "Có vẻ như chương trình bị lỗi !!!", "Thông báo", JOptionPane.CLOSED_OPTION, JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        JOptionPane.showConfirmDialog(this, "Email, sdt, cmnd không được khớp bất kì nhân viên nào !", "Thông báo", JOptionPane.CLOSED_OPTION, JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_btnThemMoiMouseClicked

    private void Text_sdtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Text_sdtKeyPressed
        // TODO add your handling code here:
        if(Character.isLetter(evt.getKeyChar()) || Text_sdt.getText().length() == 11 && evt.getKeyChar() != KeyEvent.VK_BACK_SPACE){
            Text_sdt.setEditable(false);
            return;
        }
        Text_sdt.setEditable(true);
        Text_sdt.setCaretPosition(Text_sdt.getText().length());
        
    }//GEN-LAST:event_Text_sdtKeyPressed

    private void Text_cmndKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Text_cmndKeyPressed
        // TODO add your handling code here:
        if(Character.isLetter(evt.getKeyChar()) || Text_cmnd.getText().length() == 12 && evt.getKeyChar() != KeyEvent.VK_BACK_SPACE){
            Text_cmnd.setEditable(false);
            return;
        }
        Text_cmnd.setEditable(true);
        Text_cmnd.setCaretPosition(Text_cmnd.getText().length());
    }//GEN-LAST:event_Text_cmndKeyPressed

    private void Text_sdtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Text_sdtMouseClicked
        // TODO add your handling code here:
        
        Text_sdt.setEditable(true);
        Text_sdt.setCaretPosition(Text_sdt.getText().length());
    }//GEN-LAST:event_Text_sdtMouseClicked

    private void Text_cmndMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Text_cmndMouseClicked
        // TODO add your handling code here:
        Text_cmnd.setEditable(true);
        Text_cmnd.setCaretPosition(Text_cmnd.getText().length());
    }//GEN-LAST:event_Text_cmndMouseClicked

    private void btnXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaMouseClicked
        // TODO add your handling code here:
        if(Table_nhanVien.getSelectedRowCount() == 1){
            int numRow = Table_nhanVien.getSelectedRow();
            String maNVselected = Table_nhanVien.getValueAt(numRow, 0).toString();
            if(this.maNV.equals(maNVselected)){
                JOptionPane.showConfirmDialog(this, "Không thể xoá nhân viên đang hiện hành !!!", "Thông báo", JOptionPane.CLOSED_OPTION, JOptionPane.ERROR_MESSAGE);
            }
            else{
                if(JOptionPane.showConfirmDialog(this, "Hãy suy nghĩ kĩ, bạn muốn xoá nhân viên này ?", "Thông báo", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.OK_OPTION){
                    NhanVien_DAO.xoaNhanVien(maNVselected);
                    this.loadTableNhanVien();
                }
            }
        }
    }//GEN-LAST:event_btnXoaMouseClicked

    private void btnSuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaMouseClicked
        // TODO add your handling code here:
        ArrayList<JTextField> l_TextFields = this.l_TextF();
        for(JTextField textF : l_TextFields){
            if(textF.getText().equals("") || Picker_ngaySinh.getDate().equals("")){
                JOptionPane.showConfirmDialog(this, "Hãy nhập đầy đủ dữ liệu", "Thông báo", JOptionPane.CLOSED_OPTION, JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
        
        String MaNV = Text_maNV.getText();
        String hoTen = Text_tenNV.getText();
        String gioiTinh = radioNam.isSelected() ? radioNam.getText() : radioNu.getText();
        String email = Text_Email.getText();
        String sdt = Text_sdt.getText();
        String cmnd = Text_cmnd.getText();
        String diaChi = Text_DiaChi.getText();
        String chucVu = Cbb_chucVu.getSelectedItem().toString();
        String ngaySinh = new SimpleDateFormat("yyyy-MM-dd").format(Picker_ngaySinh.getDate());
        
        int result = NhanVien_DAO.checkUpdateNhanVien(MaNV, email, sdt, cmnd);
        if(result == 0){
            if(JOptionPane.showConfirmDialog(this, "Hãy kiểm tra thật kĩ trước khi nhấn ok !!!", "Thông báo", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE) == JOptionPane.OK_OPTION){
                int resultUpdate = NhanVien_DAO.updateNhanVien(MaNV, hoTen, ngaySinh, gioiTinh, email, sdt, cmnd, diaChi, chucVu);
                this.loadTableNhanVien();
                if(resultUpdate <= 0){
                    JOptionPane.showConfirmDialog(this, "Chương trình lỗi cập nhật !!!", "Thông báo", JOptionPane.CLOSED_OPTION, JOptionPane.ERROR_MESSAGE);
                }
            }
            return;
        }
        else{
            if(result == -1){
                JOptionPane.showConfirmDialog(this, "Có vẻ như đã xảy ra lỗi !!!", "Thông báo", JOptionPane.CLOSED_OPTION, JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        
        JOptionPane.showConfirmDialog(this, "Email, sdt, cmnd không được khớp bất kì nhân viên nào !", "Thông báo", JOptionPane.CLOSED_OPTION, JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_btnSuaMouseClicked

    private void Text_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Text_searchKeyReleased
        // TODO add your handling code here:
        if(radioTheoTen.isSelected()){
            this.searchTheoTen();
        }
        else if(radioTheoSdt.isSelected()){
            this.searchTheoSdt();
        }
        else{
            this.searchTheoCMND();
        }
    }//GEN-LAST:event_Text_searchKeyReleased

    private void searchTheoTen(){
        
        DefaultTableModel tableModel = (DefaultTableModel)Table_nhanVien.getModel();
        
        tableModel.setRowCount(0);
        
        for(NhanVien_DTO nhanvien : this.l_nhanviens){
            if(nhanvien.getTenNhanVien().contains(Text_search.getText())){
                tableModel.addRow(new String[] {
                    nhanvien.getMaNV(),
                    nhanvien.getTenNhanVien(),
                    new SimpleDateFormat("dd/MM/yyyy").format(nhanvien.getNgaySinh()),
                    nhanvien.getGioiTinh(),
                    nhanvien.getEmail(),
                    nhanvien.getSdt(),
                    nhanvien.getCmnd(),
                    nhanvien.getDiaChi(),
                    nhanvien.getChucVu()   
                });
            }
        }
    }
    
    private void searchTheoSdt(){
        
        DefaultTableModel tableModel = (DefaultTableModel)Table_nhanVien.getModel();
        
        tableModel.setRowCount(0);
        
        for(NhanVien_DTO nhanvien : this.l_nhanviens){
            if(nhanvien.getSdt().contains(Text_search.getText())){
                tableModel.addRow(new String[] {
                    nhanvien.getMaNV(),
                    nhanvien.getTenNhanVien(),
                    new SimpleDateFormat("dd/MM/yyyy").format(nhanvien.getNgaySinh()),
                    nhanvien.getGioiTinh(),
                    nhanvien.getEmail(),
                    nhanvien.getSdt(),
                    nhanvien.getCmnd(),
                    nhanvien.getDiaChi(),
                    nhanvien.getChucVu()   
                });
            }
        }
    }
    
    private void searchTheoCMND(){
        
        DefaultTableModel tableModel = (DefaultTableModel)Table_nhanVien.getModel();
        
        tableModel.setRowCount(0);
        
        for(NhanVien_DTO nhanvien : this.l_nhanviens){
            if(nhanvien.getCmnd().contains(Text_search.getText())){
                tableModel.addRow(new String[] {
                    nhanvien.getMaNV(),
                    nhanvien.getTenNhanVien(),
                    new SimpleDateFormat("dd/MM/yyyy").format(nhanvien.getNgaySinh()),
                    nhanvien.getGioiTinh(),
                    nhanvien.getEmail(),
                    nhanvien.getSdt(),
                    nhanvien.getCmnd(),
                    nhanvien.getDiaChi(),
                    nhanvien.getChucVu()   
                });
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Cbb_chucVu;
    private javax.swing.JTable Table_nhanVien;
    private javax.swing.JTextField Text_DiaChi;
    private javax.swing.JTextField Text_Email;
    private javax.swing.JTextField Text_cmnd;
    private javax.swing.JTextField Text_maNV;
    private javax.swing.JTextField Text_sdt;
    private javax.swing.JTextField Text_search;
    private javax.swing.JTextField Text_tenNV;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThemMoi;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btn_TaiKhoanNV;
    private javax.swing.JLabel centerHome;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radioNam;
    private javax.swing.JRadioButton radioNu;
    private javax.swing.JRadioButton radioTheoCMND;
    private javax.swing.JRadioButton radioTheoSdt;
    private javax.swing.JRadioButton radioTheoTen;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
