/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.Sach_DAO;
import DAO.TheLoai_DAO;
import DTO.Sach_DTO;
import DTO.TheLoai_DTO;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JSpinner.DefaultEditor;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nguye
 */
public class Sach_GUI extends javax.swing.JFrame {
    private TrangChu_GUI trangChu_GUI = null;
    private String Quyen = null;
    private ArrayList<Sach_DTO> l_Sachs = null;

    /**
     * Creates new form SACH_GUI
     */
    public Sach_GUI(TrangChu_GUI trangChu_GUI, String Quyen) {
        this.Quyen = Quyen;
        this.trangChu_GUI = trangChu_GUI;
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Quản lí sách");
        this.setVisible(true);
        
        spin_SoLuong.setValue(1);
        
        if(!this.Quyen.equals("Admin")){
            btn_ThemMoi.setEnabled(false);
            btn_Sua.setEnabled(false);
            btn_Xoa.setEnabled(false);
            panel_ThaoTac.setEnabled(false);
        }
        
        this.title.setHorizontalAlignment(SwingConstants.CENTER);
        this.title.setVerticalAlignment(SwingConstants.CENTER);
        
        ((DefaultEditor)spin_SoLuong.getEditor()).getTextField().setEditable(false);
       
        picker_NgayXuatBan.setDate(Date.from(Instant.now()));
        
        this.loadAllCbb();
        this.loadTableSach();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        text_tenSach = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        text_gia = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        text_TacGia = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        spin_SoLuong = new javax.swing.JSpinner();
        text_maSach = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        cbb_TheLoai = new javax.swing.JComboBox<>();
        text_NhaXuatBan = new javax.swing.JTextField();
        panel_ThaoTac = new javax.swing.JPanel();
        btn_ThemMoi = new javax.swing.JButton();
        btn_LamMoi = new javax.swing.JButton();
        btn_Sua = new javax.swing.JButton();
        btn_Xoa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Sach = new javax.swing.JTable();
        title = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        text_Search = new javax.swing.JTextField();
        radio_TacGia = new javax.swing.JRadioButton();
        radio_TenSach = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        cbb_NhaXuatBan_Srch = new javax.swing.JComboBox<>();
        btn_TheLoaiSach = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("THÔNG TIN SÁCH"));
        jPanel2.setForeground(new java.awt.Color(240, 240, 240));

        text_tenSach.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setText("Tên sách:");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("Giá:");

        text_gia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        text_gia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                text_giaKeyPressed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setText("Số lượng:");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setText("Tác giả:");

        text_TacGia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setText("Ngày xuất bản:");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setText("Nhà xuất bản:");

        spin_SoLuong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        spin_SoLuong.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spin_SoLuongStateChanged(evt);
            }
        });

        text_maSach.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setText("Mã sách:");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setText("Thể loại:");

        cbb_TheLoai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbb_TheLoai.setPreferredSize(new java.awt.Dimension(221, 26));

        text_NhaXuatBan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel21))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                            .addComponent(spin_SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(170, 170, 170))
                                        .addComponent(jLabel17)
                                        .addComponent(jLabel18)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(16, 16, 16)
                                            .addComponent(text_gia, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel20))
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel24))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text_maSach, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_tenSach, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_TacGia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbb_TheLoai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_NhaXuatBan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text_maSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text_tenSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text_gia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spin_SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text_TacGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text_NhaXuatBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbb_TheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panel_ThaoTac.setBorder(javax.swing.BorderFactory.createTitledBorder("THAO TÁC"));

        btn_ThemMoi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_ThemMoi.setText("Thêm mới");
        btn_ThemMoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ThemMoiMouseClicked(evt);
            }
        });
        btn_ThemMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemMoiActionPerformed(evt);
            }
        });

        btn_LamMoi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_LamMoi.setText("Làm mới");
        btn_LamMoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_LamMoiMouseClicked(evt);
            }
        });

        btn_Sua.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_Sua.setText("Sửa");
        btn_Sua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_SuaMouseClicked(evt);
            }
        });

        btn_Xoa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_Xoa.setText("Xoá");
        btn_Xoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_XoaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_ThaoTacLayout = new javax.swing.GroupLayout(panel_ThaoTac);
        panel_ThaoTac.setLayout(panel_ThaoTacLayout);
        panel_ThaoTacLayout.setHorizontalGroup(
            panel_ThaoTacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ThaoTacLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_ThaoTacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_Xoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_ThemMoi, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(panel_ThaoTacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_LamMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Sua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panel_ThaoTacLayout.setVerticalGroup(
            panel_ThaoTacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_ThaoTacLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panel_ThaoTacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ThemMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_ThaoTacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_LamMoi, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(btn_Xoa, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addContainerGap())
        );

        Table_Sach.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Table_Sach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        Table_Sach.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        Table_Sach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_SachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table_Sach);

        title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(0, 102, 204));
        title.setText("QUẢN LÝ SÁCH");
        title.setOpaque(true);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("TÌM KIẾM & LIỆT KÊ"));
        jPanel5.setToolTipText("");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Tìm kiếm:");

        text_Search.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        text_Search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                text_SearchKeyReleased(evt);
            }
        });

        radio_TacGia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radio_TacGia.setText("Theo tác giả");
        radio_TacGia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                radio_TacGiaMousePressed(evt);
            }
        });

        radio_TenSach.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radio_TenSach.setSelected(true);
        radio_TenSach.setText("Theo tên sách");
        radio_TenSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                radio_TenSachMousePressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Thể loai:");

        cbb_NhaXuatBan_Srch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbb_NhaXuatBan_Srch.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbb_NhaXuatBan_SrchItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(radio_TenSach)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radio_TacGia)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(text_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbb_NhaXuatBan_Srch, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radio_TacGia)
                    .addComponent(radio_TenSach))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbb_NhaXuatBan_Srch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(text_Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        btn_TheLoaiSach.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_TheLoaiSach.setText("Thể loại sách");
        btn_TheLoaiSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_TheLoaiSachMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_TheLoaiSach, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panel_ThaoTac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_TheLoaiSach))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel_ThaoTac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadAllCbb(){
        ArrayList<TheLoai_DTO> l_TheLoais = TheLoai_DAO.getListTheLoai();

        cbb_NhaXuatBan_Srch.addItem("Mặc định");
        for(TheLoai_DTO theloai : l_TheLoais){
            cbb_TheLoai.addItem(theloai.getTl_Sach());
            cbb_NhaXuatBan_Srch.addItem(theloai.getTl_Sach());
        }
   
    }
    
    
    private void addColumnTable(){
        DefaultTableModel tableModel = (DefaultTableModel)Table_Sach.getModel();
        tableModel.setColumnIdentifiers(new String[]{
            "Mã sách", "Tên sách", "Giá", "Số lượng", "Tác giả", "Ngày xuất bản", "Nhà xuất bản", "Thể loại"
        });
        
        DefaultTableColumnModel tableColumnModel = (DefaultTableColumnModel)Table_Sach.getColumnModel();
        tableColumnModel.getColumn(0).setPreferredWidth(100);
        tableColumnModel.getColumn(1).setPreferredWidth(200);
        tableColumnModel.getColumn(2).setPreferredWidth(120);
        tableColumnModel.getColumn(3).setPreferredWidth(100);
        tableColumnModel.getColumn(4).setPreferredWidth(150);
        tableColumnModel.getColumn(5).setPreferredWidth(150);
        tableColumnModel.getColumn(6).setPreferredWidth(150);
        tableColumnModel.getColumn(7).setPreferredWidth(150);
        
        Table_Sach.getTableHeader().setFont(new Font("Arial", Font.BOLD, 15));
    }
    
    private void loadTableSach(){
        this.addColumnTable();
        
        DefaultTableModel tableModel = (DefaultTableModel)Table_Sach.getModel();
        tableModel.setRowCount(0);
        
        this.l_Sachs = Sach_DAO.getListSach();
        
        for(Sach_DTO sach : this.l_Sachs){
            tableModel.addRow(new String[]{
                sach.getMaSach(),
                sach.getTenSach(),
                String.valueOf(sach.getGia()),
                String.valueOf(sach.getSoLuong()),
                sach.getTacGia(),
                new SimpleDateFormat("dd/MM/yyyy").format(sach.getNgayXuatBan()),
                sach.getNhaXuatBan(),
                sach.getTheLoai()
            });
        }
    }
    
    private void btn_ThemMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemMoiActionPerformed
        // TODO add your handling code here:
   
    }//GEN-LAST:event_btn_ThemMoiActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        
        if(JOptionPane.showConfirmDialog(this,"Bạn muốn quay lại trang chính ?", "Thông báo", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.OK_OPTION){
            this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            this.trangChu_GUI.setEnabled(true);
            return;
        }
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }//GEN-LAST:event_formWindowClosing

    private void btn_TheLoaiSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_TheLoaiSachMouseClicked
        // TODO add your handling code here:
        new TheLoai_GUI(this, this.Quyen);
        this.setVisible(false);
    }//GEN-LAST:event_btn_TheLoaiSachMouseClicked

    private ArrayList<JTextField> l_textFeild(){
        ArrayList<JTextField> listT = new ArrayList<JTextField>();
        listT.add(text_NhaXuatBan);
        listT.add(text_TacGia);
        listT.add(text_maSach);
        listT.add(text_tenSach);
        listT.add(text_gia);
        return listT;
    }
    
    private boolean checkEmptyText(){
        ArrayList<JTextField> listT = this.l_textFeild();
        for(JTextField textF : listT){
            if(textF.getText().equals("")){
                JOptionPane.showConfirmDialog(this, "Hãy nhập đầy đủ thông tin !!!", "Thông báo", JOptionPane.CLOSED_OPTION, JOptionPane.WARNING_MESSAGE);
                return true;
            }
        }
        return false;
    }
    
    private void btn_ThemMoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ThemMoiMouseClicked
        // TODO add your handling code here:
        if(btn_ThemMoi.isEnabled()){
            if(this.checkEmptyText() == true){
                return;
            }
            
            String maSach = text_maSach.getText();
            String tenSach = text_tenSach.getText();
            String gia = text_gia.getText();
            String soLuong = spin_SoLuong.getValue().toString();
            String ngayXuatBan = new SimpleDateFormat("yyyy-MM-dd").format(picker_NgayXuatBan.getDate());
            String tacGia = text_TacGia.getText();
            String nhaXuatBan = text_NhaXuatBan.getText();
            String theLoai = TheLoai_DAO.getMaTheLoai(cbb_TheLoai.getSelectedItem().toString());
            
            if(JOptionPane.showConfirmDialog(this, "Đồng ý thêm mới ?", "Thông báo", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.OK_OPTION){
                int result = Sach_DAO.addNewSach(maSach, tenSach, gia, soLuong, tacGia, ngayXuatBan, nhaXuatBan, theLoai);
               
                this.ResetAllPage();
                
                if(result <= 0){
                    JOptionPane.showConfirmDialog(this, "Có vẻ như xảy ra lỗi !!!", "Thông báo", JOptionPane.CLOSED_OPTION, JOptionPane.ERROR_MESSAGE);
                }
            }        
        }
    }//GEN-LAST:event_btn_ThemMoiMouseClicked

    private void Table_SachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_SachMouseClicked
        // TODO add your handling code here:
        if(Table_Sach.getSelectedRowCount() == 1){
            text_maSach.setFocusable(false);
            int numRow = Table_Sach.getSelectedRow();
            
            ArrayList<String> valueColumn = new ArrayList<String>();
 
            for(int i = 0; i < Table_Sach.getColumnCount(); i++){
                valueColumn.add(Table_Sach.getValueAt(numRow, i).toString());
            }
            
            text_maSach.setText(valueColumn.get(0));
            text_tenSach.setText(valueColumn.get(1));
            text_gia.setText(valueColumn.get(2));
            spin_SoLuong.setValue(Integer.parseInt(valueColumn.get(3)));
            text_TacGia.setText(valueColumn.get(4));
            try {
                picker_NgayXuatBan.setDate(new SimpleDateFormat("dd/MM/yyyy").parse(valueColumn.get(5)));
            } catch (Exception e) {
            }
            text_NhaXuatBan.setText(valueColumn.get(6));
            cbb_TheLoai.setSelectedItem(valueColumn.get(7));
        }
    }//GEN-LAST:event_Table_SachMouseClicked

    private void spin_SoLuongStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spin_SoLuongStateChanged
        // TODO add your handling code here:
        if(Integer.valueOf(spin_SoLuong.getValue().toString()) < 1){
            spin_SoLuong.setValue(1);
        }
        else{
            if(Integer.valueOf(spin_SoLuong.getValue().toString()) > 50){
                spin_SoLuong.setValue(50);
            }
        }
    }//GEN-LAST:event_spin_SoLuongStateChanged

    private void btn_LamMoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LamMoiMouseClicked
        // TODO add your handling code here:
        this.ResetAllPage();
    }//GEN-LAST:event_btn_LamMoiMouseClicked

    private void btn_SuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SuaMouseClicked
        // TODO add your handling code here:

        if(Table_Sach.getSelectedRowCount() == 1){
            if(JOptionPane.showConfirmDialog(this, "Đồng ý sửa sách này ?", "Thông báo", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.OK_OPTION){
                String maSach = text_maSach.getText();
                String tenSach = text_tenSach.getText();
                String gia = text_gia.getText();
                String soLuong = spin_SoLuong.getValue().toString();
                String ngayXuatBan = new SimpleDateFormat("yyyy-MM-dd").format(picker_NgayXuatBan.getDate());
                String tacGia = text_TacGia.getText();
                String nhaXuatBan = text_NhaXuatBan.getText();
                String theLoai = TheLoai_DAO.getMaTheLoai(cbb_TheLoai.getSelectedItem().toString());

                int result = Sach_DAO.updateSach(maSach, tenSach, gia, soLuong, tacGia, ngayXuatBan, nhaXuatBan, theLoai);
                this.ResetAllPage();

                if(result <= 0){
                    JOptionPane.showConfirmDialog(this, "Có vẻ như xảy ra lỗi !!!", "Thông báo", JOptionPane.CLOSED_OPTION, JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        else{
            JOptionPane.showConfirmDialog(this, "Hãy chọn sách muốn sửa !!!", "Thông báo", JOptionPane.CLOSED_OPTION, JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btn_SuaMouseClicked

    private void btn_XoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_XoaMouseClicked
        // TODO add your handling code here:
        
        if(Table_Sach.getSelectedRowCount() == 1){
            if(JOptionPane.showConfirmDialog(this, "Đồng ý xoá sách này ?", "Thông báo", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.OK_OPTION){
                String maSach = text_maSach.getText();
                int result = Sach_DAO.xoaSach(maSach);
                
                this.ResetAllPage();
                
                if(result <= 0){
                    JOptionPane.showConfirmDialog(this, "Có vẻ như xảy ra lỗi !!!", "Thông báo", JOptionPane.CLOSED_OPTION, JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        else{
            JOptionPane.showConfirmDialog(this, "Hãy chọn sách muốn xoá !!!", "Thông báo", JOptionPane.CLOSED_OPTION, JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btn_XoaMouseClicked

    private void radio_TenSachMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radio_TenSachMousePressed
        // TODO add your handling code here:
        radio_TacGia.setSelected(false);
        this.searchTheoTenSach();
    }//GEN-LAST:event_radio_TenSachMousePressed

    private void radio_TacGiaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radio_TacGiaMousePressed
        // TODO add your handling code here:
        radio_TenSach.setSelected(false);
        this.searchTheoTacGia();
    }//GEN-LAST:event_radio_TacGiaMousePressed

    private void cbb_NhaXuatBan_SrchItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbb_NhaXuatBan_SrchItemStateChanged
        // TODO add your handling code here:
        if(radio_TenSach.isSelected()){
            this.searchTheoTenSach();
        }
        else{
            if(radio_TacGia.isSelected()){
                this.searchTheoTacGia();
            }
        }
    }//GEN-LAST:event_cbb_NhaXuatBan_SrchItemStateChanged

    private void text_SearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_SearchKeyReleased
        // TODO add your handling code here:
        if(radio_TenSach.isSelected()){
            this.searchTheoTenSach();
        }
        else{
            if(radio_TacGia.isSelected()){
                this.searchTheoTacGia();
            }
        }
    }//GEN-LAST:event_text_SearchKeyReleased

    private void text_giaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_giaKeyPressed
        // TODO add your handling code here:
        if(Character.isLetter(evt.getKeyChar()) && evt.getKeyChar() != KeyEvent.VK_BACK_SPACE){
            text_gia.setEditable(false);
        }
        else{
            text_gia.setEditable(true);
        }
    }//GEN-LAST:event_text_giaKeyPressed

    private void searchTheoTacGia(){
        DefaultTableModel tableModel = (DefaultTableModel)Table_Sach.getModel();
        tableModel.setRowCount(0);
        
        if(cbb_NhaXuatBan_Srch.getSelectedItem().equals("Mặc định")){
            if(this.l_Sachs == null){
                return;
            }
            
            this.SearchTheoTacGiaAndMacDinh(tableModel);
        }
        else{
            String theLoai = cbb_NhaXuatBan_Srch.getSelectedItem().toString();
            this.SearchTheoTacGiaAndTheLoai(tableModel, theLoai);
        }
    }
    
    private void SearchTheoTacGiaAndTheLoai(DefaultTableModel tableModel, String theLoai){
        for(Sach_DTO sach : this.l_Sachs){
            if(sach.getTacGia().contains(text_Search.getText()) && sach.getTheLoai().equals(theLoai)){
                tableModel.addRow(new String[]{
                    sach.getMaSach(),
                    sach.getTenSach(),
                    String.valueOf(sach.getGia()),
                    String.valueOf(sach.getSoLuong()),
                    sach.getTacGia(),
                    String.valueOf(sach.getNgayXuatBan()),
                    sach.getNhaXuatBan(),
                    sach.getTheLoai()
                });
            } 
        }
    }
    
    private void SearchTheoTacGiaAndMacDinh(DefaultTableModel tableModel){
        for(Sach_DTO sach : this.l_Sachs){
            if(sach.getTacGia().contains(text_Search.getText())){
                tableModel.addRow(new String[]{
                    sach.getMaSach(),
                    sach.getTenSach(),
                    String.valueOf(sach.getGia()),
                    String.valueOf(sach.getSoLuong()),
                    sach.getTacGia(),
                    String.valueOf(sach.getNgayXuatBan()),
                    sach.getNhaXuatBan(),
                    sach.getTheLoai()
                });
            } 
        }
    }
    
    private void searchTheoTenSach(){
        DefaultTableModel tableModel = (DefaultTableModel)Table_Sach.getModel();
        tableModel.setRowCount(0);
        
        if(cbb_NhaXuatBan_Srch.getSelectedItem().equals("Mặc định")){
            if(this.l_Sachs == null){
                return;
            }
            
            this.searchTheoTenSachAndMacDinh(tableModel);
        }
        else{
            String theLoai = cbb_NhaXuatBan_Srch.getSelectedItem().toString();
            this.searchTheoTenSachAndTheLoai(tableModel, theLoai);
        }
    }
    
    private void searchTheoTenSachAndMacDinh(DefaultTableModel tableModel){
        for(Sach_DTO sach : this.l_Sachs){
            if(sach.getTenSach().contains(text_Search.getText())){
                tableModel.addRow(new String[]{
                    sach.getMaSach(),
                    sach.getTenSach(),
                    String.valueOf(sach.getGia()),
                    String.valueOf(sach.getSoLuong()),
                    sach.getTacGia(),
                    String.valueOf(sach.getNgayXuatBan()),
                    sach.getNhaXuatBan(),
                    sach.getTheLoai()
                });
            } 
        }
    }
    
    private void searchTheoTenSachAndTheLoai(DefaultTableModel tableModel, String theLoai){
        for(Sach_DTO sach : this.l_Sachs){
            if(sach.getTenSach().contains(text_Search.getText()) && sach.getTheLoai().equals(theLoai)){
                tableModel.addRow(new String[]{
                    sach.getMaSach(),
                    sach.getTenSach(),
                    String.valueOf(sach.getGia()),
                    String.valueOf(sach.getSoLuong()),
                    sach.getTacGia(),
                    String.valueOf(sach.getNgayXuatBan()),
                    sach.getNhaXuatBan(),
                    sach.getTheLoai()
                });
            } 
        }
    }
    
    private void ResetAllPage(){
        ArrayList<JTextField> l_textFields = this.l_textFeild();
        for(JTextField item : l_textFields){
            item.setText("");
        }
        
        text_maSach.setFocusable(true);
        spin_SoLuong.setValue(1);
        picker_NgayXuatBan.setDate(Date.from(Instant.now()));
       
        cbb_TheLoai.setSelectedItem(cbb_TheLoai.getItemAt(0));
        cbb_NhaXuatBan_Srch.setSelectedItem(cbb_NhaXuatBan_Srch.getItemAt(0));
        this.loadTableSach();
        
        radio_TenSach.setSelected(true);
        radio_TacGia.setSelected(false);
        text_Search.setText("");
    }
    
    public void reSetALL(){
        new Sach_GUI(this.trangChu_GUI, this.Quyen);
        this.dispose();
    }
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table_Sach;
    private javax.swing.JButton btn_LamMoi;
    private javax.swing.JButton btn_Sua;
    private javax.swing.JButton btn_TheLoaiSach;
    private javax.swing.JButton btn_ThemMoi;
    private javax.swing.JButton btn_Xoa;
    private javax.swing.JComboBox<String> cbb_NhaXuatBan_Srch;
    private javax.swing.JComboBox<String> cbb_TheLoai;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel_ThaoTac;
    private javax.swing.JRadioButton radio_TacGia;
    private javax.swing.JRadioButton radio_TenSach;
    private javax.swing.JSpinner spin_SoLuong;
    private javax.swing.JTextField text_NhaXuatBan;
    private javax.swing.JTextField text_Search;
    private javax.swing.JTextField text_TacGia;
    private javax.swing.JTextField text_gia;
    private javax.swing.JTextField text_maSach;
    private javax.swing.JTextField text_tenSach;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
