/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.TaiKhoan_DAO;
import DTO.TaiKhoan_DTO;
import java.awt.Font;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nguye
 */
public class TaiKhoan_GUI extends javax.swing.JFrame {
    private NhanVien_GUI nhanVien_GUI = null;
    private ArrayList<String[]> l_taiKhoans = null;
    private ArrayList<String[]> l_chuaTaiKhoan = null;
    private String maNV = null;
    /**
     * Creates new form TaiKhoan_GUI
     */
    public TaiKhoan_GUI(NhanVien_GUI nhanVien_GUI, String maNV) {
        this.maNV = maNV;
        this.nhanVien_GUI = nhanVien_GUI;
        initComponents();
        this.setTitle("Quản lý tài khoản nhân viên");
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        
        title_TaiKhoan.setHorizontalAlignment(SwingConstants.CENTER);
        title_TaiKhoan.setHorizontalTextPosition(SwingConstants.CENTER);
        title_DangKy.setHorizontalAlignment(SwingConstants.CENTER);
        title_DangKy.setHorizontalTextPosition(SwingConstants.CENTER);
        
        ImageIcon imageicon = new ImageIcon("src/Pictures/nhung-quyen-sach-hay-nhat-ve-dich-thuat.jpg");
        Image image = imageicon.getImage().getScaledInstance(imageDangKy.getWidth(), imageDangKy.getHeight(), Image.SCALE_SMOOTH);
        
        imageDangKy.setIcon(new ImageIcon(image));
        
        for(String item : new String[]{"User", "Admin"}){
            Cbb_QuyenNV.addItem(item);
        }
        
        this.loadTableTaiKhoan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btn_Xoa = new javax.swing.JButton();
        btnLamMoi_Left = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_TaiKhoan = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        text_search = new javax.swing.JTextField();
        radio_DaCoTK = new javax.swing.JRadioButton();
        radio_chuaCoDK = new javax.swing.JRadioButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        text_maNV = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        text_tenNhanVien = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        text_cmnd = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        text_tenTaiKhoan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        text_matKhau = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        text_matKhauMoi = new javax.swing.JTextField();
        btn_doiMatKhau = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Cbb_QuyenNV = new javax.swing.JComboBox<>();
        btn_capNhatQuyen = new javax.swing.JButton();
        btn_showPassword = new javax.swing.JButton();
        title_DangKy = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        text_maNV_DK = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        text_username_DK = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        imageDangKy = new javax.swing.JLabel();
        btn_DangKy = new javax.swing.JButton();
        btnLamMoi_Right = new javax.swing.JButton();
        text_password_DK = new javax.swing.JPasswordField();
        text_againPassword_DK = new javax.swing.JPasswordField();
        title_TaiKhoan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("THAO TÁC"));

        btn_Xoa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_Xoa.setText("Xoá");
        btn_Xoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_XoaMouseClicked(evt);
            }
        });

        btnLamMoi_Left.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLamMoi_Left.setText("làm mới");
        btnLamMoi_Left.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLamMoi_LeftMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLamMoi_Left, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnLamMoi_Left, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(btn_Xoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        table_TaiKhoan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        table_TaiKhoan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        table_TaiKhoan.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        table_TaiKhoan.setRowHeight(20);
        table_TaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_TaiKhoanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_TaiKhoan);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("TÌM KIẾM & TUỲ CHỌN"));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Tìm kiếm:");

        text_search.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        text_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                text_searchKeyReleased(evt);
            }
        });

        radio_DaCoTK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radio_DaCoTK.setSelected(true);
        radio_DaCoTK.setText("Đã có tài khoản");
        radio_DaCoTK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                radio_DaCoTKMousePressed(evt);
            }
        });

        radio_chuaCoDK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radio_chuaCoDK.setText("Chưa có tài khoản");
        radio_chuaCoDK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                radio_chuaCoDKMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(radio_DaCoTK)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radio_chuaCoDK)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(text_search))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radio_DaCoTK)
                    .addComponent(radio_chuaCoDK))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(text_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addContainerGap())
        );

        jPanel10.setFocusable(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Mã nhân viên:");

        text_maNV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        text_maNV.setFocusable(false);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Tên nhân viên:");

        text_tenNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        text_tenNhanVien.setFocusable(false);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("CMND:");

        text_cmnd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        text_cmnd.setFocusable(false);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Tên tài khoản:");

        text_tenTaiKhoan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        text_tenTaiKhoan.setFocusable(false);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Mật khẩu:");

        text_matKhau.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        text_matKhau.setFocusable(false);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Mật khẩu mới:");

        text_matKhauMoi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btn_doiMatKhau.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_doiMatKhau.setText("Đổi mật khẩu");
        btn_doiMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_doiMatKhauMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Quyền:");

        Cbb_QuyenNV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btn_capNhatQuyen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_capNhatQuyen.setText("Cập nhật");
        btn_capNhatQuyen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_capNhatQuyenMouseClicked(evt);
            }
        });

        btn_showPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_showPassword.setText("Hiện");
        btn_showPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_showPasswordMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_showPasswordMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text_matKhauMoi)
                            .addComponent(text_tenTaiKhoan)
                            .addComponent(text_maNV)
                            .addComponent(text_cmnd)
                            .addComponent(text_tenNhanVien)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(text_matKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_showPassword))))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(47, 47, 47)
                                .addComponent(Cbb_QuyenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_capNhatQuyen))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(btn_doiMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Cbb_QuyenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_capNhatQuyen))
                .addGap(30, 30, 30)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(text_maNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(text_tenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(text_cmnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(text_tenTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_showPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_matKhau)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(text_matKhauMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_doiMatKhau)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        title_DangKy.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        title_DangKy.setForeground(new java.awt.Color(0, 102, 204));
        title_DangKy.setText("ĐĂNG KÝ TÀI KHOẢN");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Mã nhân viên:");

        text_maNV_DK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        text_maNV_DK.setFocusable(false);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Tên tài khoản:");

        text_username_DK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Mật khẩu:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Nhập lại mật khẩu:");

        btn_DangKy.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_DangKy.setText("Đăng ký");
        btn_DangKy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_DangKyMouseClicked(evt);
            }
        });

        btnLamMoi_Right.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLamMoi_Right.setText("làm mới");
        btnLamMoi_Right.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLamMoi_RightMouseClicked(evt);
            }
        });

        text_password_DK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        text_againPassword_DK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel9))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text_maNV_DK, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                            .addComponent(text_username_DK)
                            .addComponent(text_password_DK)
                            .addComponent(text_againPassword_DK)))
                    .addComponent(imageDangKy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(btnLamMoi_Right, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_DangKy, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imageDangKy, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLamMoi_Right)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel8))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(text_maNV_DK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(text_username_DK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(text_password_DK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(text_againPassword_DK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_DangKy, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(941, 941, 941))
        );

        title_TaiKhoan.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        title_TaiKhoan.setForeground(new java.awt.Color(0, 102, 204));
        title_TaiKhoan.setText("TÀI KHOẢN NHÂN VIÊN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(title_TaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title_DangKy, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title_DangKy, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(title_TaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this, "Bạn muốn quay lại trang nhân viên ?", "Thông báo", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.OK_OPTION){
            this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            this.nhanVien_GUI.setVisible(true);
            return;
        }
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }//GEN-LAST:event_formWindowClosing

    private void table_TaiKhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_TaiKhoanMouseClicked
        // TODO add your handling code here:
        if(table_TaiKhoan.getSelectedRowCount() == 1){
            int numRow = table_TaiKhoan.getSelectedRow();
            
            if(radio_DaCoTK.isSelected()){ 
                btn_capNhatQuyen.setEnabled(true);
    
                String maNV = table_TaiKhoan.getValueAt(numRow, 3).toString();

                if(this.maNV.equals(maNV)){
                    btn_capNhatQuyen.setEnabled(false);
                }
            
                text_maNV.setText(table_TaiKhoan.getValueAt(numRow, 3).toString());
                text_tenNhanVien.setText(table_TaiKhoan.getValueAt(numRow, 4).toString());
                Cbb_QuyenNV.setSelectedItem(table_TaiKhoan.getValueAt(numRow, 2));
                text_cmnd.setText(table_TaiKhoan.getValueAt(numRow, 5).toString());
                text_tenTaiKhoan.setText(table_TaiKhoan.getValueAt(numRow, 0).toString());
                text_matKhau.setText("*******************");
                return;
            }
            else{
                if(radio_chuaCoDK.isSelected()){
                    text_maNV_DK.setText(table_TaiKhoan.getValueAt(numRow, 0).toString());
                }
            }  
        }
    }//GEN-LAST:event_table_TaiKhoanMouseClicked

    private void btn_showPasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_showPasswordMousePressed
        // TODO add your handling code here:
        if(text_matKhau.getText().equals("")){
            return;
        }
        String password = TaiKhoan_DAO.getPassword(text_maNV.getText());
        text_matKhau.setText(password);
    }//GEN-LAST:event_btn_showPasswordMousePressed

    private void btn_showPasswordMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_showPasswordMouseReleased
        // TODO add your handling code here:
        if(text_matKhau.getText().equals("")){
            return;
        }
        text_matKhau.setText("*******************");
    }//GEN-LAST:event_btn_showPasswordMouseReleased

    private void radio_DaCoTKMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radio_DaCoTKMousePressed
        // TODO add your handling code here:
        radio_chuaCoDK.setSelected(false);
        this.loadTableTaiKhoan();
    }//GEN-LAST:event_radio_DaCoTKMousePressed

    private void radio_chuaCoDKMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radio_chuaCoDKMousePressed
        // TODO add your handling code here:
        radio_DaCoTK.setSelected(false);
        this.loadTableChuaCoTaiKhoan();
    }//GEN-LAST:event_radio_chuaCoDKMousePressed

    private void btnLamMoi_LeftMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLamMoi_LeftMouseClicked
        // TODO add your handling code here:
        Cbb_QuyenNV.setSelectedItem("User");
        text_maNV.setText("");
        text_tenNhanVien.setText("");
        text_cmnd.setText("");
        text_tenTaiKhoan.setText("");
        text_matKhau.setText("");
        text_matKhauMoi.setText("");
        radio_DaCoTK.setSelected(true);
        radio_chuaCoDK.setSelected(false);
        this.loadTableTaiKhoan();
    }//GEN-LAST:event_btnLamMoi_LeftMouseClicked

    private void btnLamMoi_RightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLamMoi_RightMouseClicked
        // TODO add your handling code here:
        text_maNV_DK.setText("");
        text_tenTaiKhoan.setText("");
        text_password_DK.setText("");
        text_againPassword_DK.setText("");
        radio_chuaCoDK.setSelected(true);
        radio_DaCoTK.setSelected(false);
        this.loadTableChuaCoTaiKhoan();
    }//GEN-LAST:event_btnLamMoi_RightMouseClicked

    private void btn_capNhatQuyenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_capNhatQuyenMouseClicked
        // TODO add your handling code here:
        if(btn_capNhatQuyen.isEnabled()){
            int numRow = table_TaiKhoan.getSelectedRow();
            String Quyen = table_TaiKhoan.getValueAt(numRow, 2).toString();
            String maNV = table_TaiKhoan.getValueAt(numRow, 3).toString();
            if(Quyen.equals(Cbb_QuyenNV.getSelectedItem().toString())){
                return;
            }

//            if(this.maNV.equals(maNV)){
//                JOptionPane.showConfirmDialog(this, "Bạn không nên làm điều này !!!", "Thông báo", JOptionPane.CLOSED_OPTION, JOptionPane.ERROR_MESSAGE);
//                return;
//
//            }

            if(JOptionPane.showConfirmDialog(this, "Xác nhận phân quyền ?", "Thông báo", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.OK_OPTION){
                int result = TaiKhoan_DAO.updateQuyen(text_maNV.getText(), Cbb_QuyenNV.getSelectedItem().toString());
                this.loadTableTaiKhoan();

                ArrayList<JTextField> l_textFields = this.listTextLeft();
                for(JTextField textField : l_textFields){
                    textField.setText("");
                }

                if(result <= 0){
                    JOptionPane.showConfirmDialog(this, "Có vẻ như xảy ra lỗi !!!", "Thông báo", JOptionPane.CLOSED_OPTION, JOptionPane.ERROR_MESSAGE);
                } 
            }
        }
    }//GEN-LAST:event_btn_capNhatQuyenMouseClicked

    private ArrayList<JTextField> listTextLeft(){
        ArrayList<JTextField> l_textFields = new ArrayList<JTextField>();
        
        l_textFields.add(text_cmnd);
        l_textFields.add(text_maNV);
        l_textFields.add(text_matKhau);
        l_textFields.add(text_matKhauMoi);
        l_textFields.add(text_tenNhanVien);
        l_textFields.add(text_tenTaiKhoan);
        
        return l_textFields;
    }
    
    private void btn_doiMatKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_doiMatKhauMouseClicked
        // TODO add your handling code here:
        if(text_matKhauMoi.getText().equals("")){
            JOptionPane.showConfirmDialog(this, "Hãy nhập mật khẩu mới !!!", "Thông báo", JOptionPane.CLOSED_OPTION, JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if(JOptionPane.showConfirmDialog(this, "Xác nhận đổi mật khẩu ?", "Thông báo", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.OK_OPTION){
            int result = TaiKhoan_DAO.changePassword(text_maNV.getText(), text_matKhauMoi.getText());
            this.loadTableTaiKhoan();
            
            ArrayList<JTextField> l_textFields = this.listTextLeft();
            for(JTextField textField : l_textFields){
                textField.setText("");
            }
            
            if(result <= 0){
                JOptionPane.showConfirmDialog(this, "Có vẻ như xảy ra lỗi !!!", "Thông báo", JOptionPane.CLOSED_OPTION, JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_doiMatKhauMouseClicked

    private void btn_XoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_XoaMouseClicked
        // TODO add your handling code here:
        
        if(text_maNV.getText().equals("")){
            JOptionPane.showConfirmDialog(this, "Hãy chọn tài khoản muốn xoá !", "Thông báo", JOptionPane.CLOSED_OPTION, JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if(text_maNV.getText().equals(this.maNV)){
            JOptionPane.showConfirmDialog(this, "Không thể xoá tài khoản đang hiện hành !!!", "Thông báo", JOptionPane.CLOSED_OPTION, JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if(JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn rằng xoá tài khoản này ?", "Thông báo", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.OK_OPTION){
            int result = TaiKhoan_DAO.xoaTaiKhoan(text_maNV.getText());
            this.loadTableTaiKhoan();
            
            ArrayList<JTextField> l_textFields = this.listTextLeft();
            for(JTextField textField : l_textFields){
                textField.setText("");
            }
            
            if(result <= 0){
                JOptionPane.showConfirmDialog(this, "Có vẻ như xảy ra lỗi !!!", "Thông báo", JOptionPane.CLOSED_OPTION, JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_XoaMouseClicked

    private void btn_DangKyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DangKyMouseClicked
        // TODO add your handling code here:
        String maNV = text_maNV_DK.getText();
        String username = text_username_DK.getText();
        String password = String.valueOf(text_password_DK.getPassword());
        String passwordAgain = String.valueOf(text_againPassword_DK.getPassword());
        
        if(maNV.equals("")){
            JOptionPane.showConfirmDialog(this, "Hãy chọn nhân viên muốn đăng ký !", "Thông báo", JOptionPane.CLOSED_OPTION, JOptionPane.WARNING_MESSAGE);
        }
        else if(username.equals("") || password.equals("") || passwordAgain.equals("")){
            JOptionPane.showConfirmDialog(this, "Hãy nhập đầy đủ thông tin !", "Thông báo", JOptionPane.CLOSED_OPTION, JOptionPane.WARNING_MESSAGE);
        }
        else if(!password.equals(passwordAgain)){
            JOptionPane.showConfirmDialog(this, "Mật khẩu không khớp nhau !", "Thông báo", JOptionPane.CLOSED_OPTION, JOptionPane.WARNING_MESSAGE);
        }
        else{
            int value = TaiKhoan_DAO.dangKyTaiKhoan(maNV, username, password);
            this.loadTableChuaCoTaiKhoan();
            if(value <= 0){
                JOptionPane.showConfirmDialog(this, "Có vẻ như xảy ra lỗi !!!", "Thông báo", JOptionPane.CLOSED_OPTION, JOptionPane.ERROR_MESSAGE);
            }
            else{
                JOptionPane.showConfirmDialog(this, "Đăng ký thành công !", "Thông báo", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE);
                text_maNV_DK.setText("");
                text_username_DK.setText("");
                text_password_DK.setText("");
                text_againPassword_DK.setText("");
            }
        }
    }//GEN-LAST:event_btn_DangKyMouseClicked

    private void text_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_searchKeyReleased
        // TODO add your handling code here:
        if(radio_DaCoTK.isSelected()){
            this.radioDaCoTaiKhoanSearch();
            return;
        }
        
        if(radio_chuaCoDK.isSelected()){
            this.radioChuaCoTaiKhoanSearch();
            return;
        }   
    }//GEN-LAST:event_text_searchKeyReleased

    private void radioDaCoTaiKhoanSearch(){
        DefaultTableModel tableModel = (DefaultTableModel)table_TaiKhoan.getModel();
        tableModel.setRowCount(0);
        for(String[] item : this.l_taiKhoans){
            if(item[3].contains(text_search.getText())){
                tableModel.addRow(item);
            }
        }
    }
    
    private void radioChuaCoTaiKhoanSearch(){
        DefaultTableModel tableModel = (DefaultTableModel)table_TaiKhoan.getModel();
        tableModel.setRowCount(0);
        for(String[] item : this.l_chuaTaiKhoan){
            if(item[0].contains(text_search.getText())){
                tableModel.addRow(item);
            }
        }
    }
    
    private void addColumnChuaTaiKhoan(){
        DefaultTableModel tableModel = (DefaultTableModel)table_TaiKhoan.getModel();
        
        tableModel.setColumnIdentifiers(new String[]{
            "Mã nhân viên", "Tên nhân viên", "CMND"
        });
        
        DefaultTableColumnModel tableColumnModel = (DefaultTableColumnModel)table_TaiKhoan.getColumnModel();
        tableColumnModel.getColumn(0).setPreferredWidth(120);
        tableColumnModel.getColumn(1).setPreferredWidth(220);
        tableColumnModel.getColumn(2).setPreferredWidth(120);
        
        table_TaiKhoan.getTableHeader().setFont(new Font("Arial", Font.BOLD, 14));
    }
    
    private void loadTableChuaCoTaiKhoan(){
        DefaultTableModel tableModel = (DefaultTableModel)table_TaiKhoan.getModel();
        tableModel.getDataVector().removeAllElements();
        
        this.addColumnChuaTaiKhoan();
        tableModel.setRowCount(0);
        
        this.l_chuaTaiKhoan = TaiKhoan_DAO.getListChuaTaiKhoan();
        for(String[] item : this.l_chuaTaiKhoan){
            tableModel.addRow(item);
        }
    }
    
    private void addColumnTableTaiKhoan(){
        DefaultTableModel tableModel = (DefaultTableModel)table_TaiKhoan.getModel();
        tableModel.setColumnIdentifiers(new String[]{
            "Tên tài khoản", "Mật khẩu", "Quyền", "Mã nhân viên", "Tên nhân viên", "CMND"
        });
        
        DefaultTableColumnModel table_ColumnModel = (DefaultTableColumnModel)table_TaiKhoan.getColumnModel();
        table_ColumnModel.getColumn(0).setPreferredWidth(150);
        table_ColumnModel.getColumn(1).setPreferredWidth(150);
        table_ColumnModel.getColumn(2).setPreferredWidth(100);
        table_ColumnModel.getColumn(2).setPreferredWidth(100);
        table_ColumnModel.getColumn(3).setPreferredWidth(120);
        table_ColumnModel.getColumn(4).setPreferredWidth(200);
        table_ColumnModel.getColumn(5).setPreferredWidth(100);
        
        table_TaiKhoan.getTableHeader().setFont(new Font("Arial", Font.BOLD, 14));
    }
    
    private void loadTableTaiKhoan(){
        DefaultTableModel tableModel = (DefaultTableModel)table_TaiKhoan.getModel();
        tableModel.getDataVector().removeAllElements();
        
        this.addColumnTableTaiKhoan();
        tableModel.setRowCount(0);
        
        this.l_taiKhoans = TaiKhoan_DAO.getListTaiKhoan();
        for(String[] tk : this.l_taiKhoans){
            tableModel.addRow(tk);
        }
    }
    
  
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Cbb_QuyenNV;
    private javax.swing.JButton btnLamMoi_Left;
    private javax.swing.JButton btnLamMoi_Right;
    private javax.swing.JButton btn_DangKy;
    private javax.swing.JButton btn_Xoa;
    private javax.swing.JButton btn_capNhatQuyen;
    private javax.swing.JButton btn_doiMatKhau;
    private javax.swing.JButton btn_showPassword;
    private javax.swing.JLabel imageDangKy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radio_DaCoTK;
    private javax.swing.JRadioButton radio_chuaCoDK;
    private javax.swing.JTable table_TaiKhoan;
    private javax.swing.JPasswordField text_againPassword_DK;
    private javax.swing.JTextField text_cmnd;
    private javax.swing.JTextField text_maNV;
    private javax.swing.JTextField text_maNV_DK;
    private javax.swing.JTextField text_matKhau;
    private javax.swing.JTextField text_matKhauMoi;
    private javax.swing.JPasswordField text_password_DK;
    private javax.swing.JTextField text_search;
    private javax.swing.JTextField text_tenNhanVien;
    private javax.swing.JTextField text_tenTaiKhoan;
    private javax.swing.JTextField text_username_DK;
    private javax.swing.JLabel title_DangKy;
    private javax.swing.JLabel title_TaiKhoan;
    // End of variables declaration//GEN-END:variables
}
