/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.CT_HoaDon_DAO;
import DAO.HoaDon_DAO;
import DAO.KhachHang_DAO;
import DAO.Sach_DAO;
import DTO.KhachHang_DTO;
import DTO.Sach_DTO;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JSpinner.DefaultEditor;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.TabExpander;

/**
 *
 * @author nguye
 */
public class TaoHoaDon_GUI extends javax.swing.JFrame {
    private TrangChu_GUI trangChu_GUI = null;
    private String maNV = null;
    private ArrayList<KhachHang_DTO> l_khachHangs = null;
    private ArrayList<Sach_DTO> l_sachs = null;
    private ArrayList<String[]> l_sachChoose;
    private ArrayList<String[]> l_sachChooseTemp;
    private int slChoose = 1;
    private int soLuongTrongKho = 1;
    private String giamGia = "0%";
    /**
     * Creates new form TaoHoaDon_GUI
     */
    public TaoHoaDon_GUI(TrangChu_GUI trangChu_GUI, String maNV) {
        this.trangChu_GUI = trangChu_GUI;
        this.maNV = maNV;
        this.l_sachChoose = new ArrayList<String[]>();
        this.l_sachChooseTemp = new ArrayList<String[]>();
        initComponents();
    
        this.setTitle("Tạo hoá đơn");
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        
        title.setHorizontalAlignment(SwingConstants.CENTER);
        title.setHorizontalTextPosition(SwingConstants.CENTER);
        
        long counHoaDon = Long.parseLong(HoaDon_DAO.getCountHoaDon()) + 1;
        title.setText("\nHOÁ ĐƠN THỨ " + counHoaDon);
        
        
        ((DefaultEditor)spin_slChoose.getEditor()).getTextField().setEditable(false);
        ((DefaultEditor)spin_slSachOrderTr.getEditor()).getTextField().setEditable(false);
        
        ImageIcon imageIcon = new ImageIcon("src/Pictures/logoStoreHome.png");
        Image image = imageIcon.getImage().getScaledInstance(logo_left.getWidth(), logo_left.getHeight(), Image.SCALE_SMOOTH);
        logo_left.setIcon(new ImageIcon(image));
        
        imageIcon = new ImageIcon("src/Pictures/imgtopleft.jpg");
        image = imageIcon.getImage().getScaledInstance(imagetopleft.getWidth(), imagetopleft.getHeight(), Image.SCALE_SMOOTH);
        imagetopleft.setIcon(new ImageIcon(image));
        
        imageIcon = new ImageIcon("src/Pictures/imgtopright.jpg");
        image = imageIcon.getImage().getScaledInstance(imagetopright.getWidth(), imagetopright.getHeight(), Image.SCALE_SMOOTH);
        imagetopright.setIcon(new ImageIcon(image));
        
        imageIcon = new ImageIcon("src/Pictures/longImgPayment.png");
        image = imageIcon.getImage().getScaledInstance(imageLong.getWidth(), imageLong.getHeight(), Image.SCALE_SMOOTH);
        imageLong.setIcon(new ImageIcon(image));
        
        spin_slSachOrderTr.setValue(1);
        spin_slChoose.setValue(1);
        
        this.loadTableChoose();
        
        addColumnTableSachOrder();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table_SachOrder = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_SachChoose = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btn_ThanhToan = new javax.swing.JButton();
        btn_XoaInOrder = new javax.swing.JButton();
        spin_slSachOrderTr = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        text_slSachOrder = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        text_sachIndexClick = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        spin_slChoose = new javax.swing.JSpinner();
        btn_ChooseSach = new javax.swing.JButton();
        btn_lamMoi = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        text_TongCong = new javax.swing.JTextField();
        radio_giamGia5 = new javax.swing.JRadioButton();
        radio_giamGia10 = new javax.swing.JRadioButton();
        radio_giamGia15 = new javax.swing.JRadioButton();
        radio_giamGia20 = new javax.swing.JRadioButton();
        radio_giamGia0 = new javax.swing.JRadioButton();
        logo_left = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        text_MaKhachMoi = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        text_TenKhachMoi = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        textArea_diaChiKhachMoi = new javax.swing.JTextArea();
        radio_NamKhachMoi = new javax.swing.JRadioButton();
        radio_NuKhachMoi = new javax.swing.JRadioButton();
        jLabel21 = new javax.swing.JLabel();
        text_SdtKhachMoi = new javax.swing.JTextField();
        imagetopleft = new javax.swing.JLabel();
        imagetopright = new javax.swing.JLabel();
        imageLong = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        table_SachOrder.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        table_SachOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        table_SachOrder.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        table_SachOrder.setRowHeight(20);
        table_SachOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_SachOrderMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_SachOrder);

        table_SachChoose.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        table_SachChoose.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        table_SachChoose.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        table_SachChoose.setRowHeight(20);
        table_SachChoose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                table_SachChooseMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(table_SachChoose);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("LỰA CHỌN"));

        btn_ThanhToan.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_ThanhToan.setText("Thanh toán");
        btn_ThanhToan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_ThanhToanMouseReleased(evt);
            }
        });

        btn_XoaInOrder.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_XoaInOrder.setText("Xoá ngay");
        btn_XoaInOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_XoaInOrderMouseClicked(evt);
            }
        });

        spin_slSachOrderTr.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        spin_slSachOrderTr.setFocusable(false);
        spin_slSachOrderTr.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spin_slSachOrderTrStateChanged(evt);
            }
        });
        spin_slSachOrderTr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                spin_slSachOrderTrKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("SL:");

        text_slSachOrder.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        text_slSachOrder.setFocusable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_XoaInOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_slSachOrder))
                    .addComponent(spin_slSachOrderTr, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 97, Short.MAX_VALUE)
                .addComponent(btn_ThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(text_slSachOrder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spin_slSachOrderTr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_XoaInOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_ThanhToan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("THIẾT LẬP"));
        jPanel2.setToolTipText("");

        text_sachIndexClick.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        text_sachIndexClick.setFocusable(false);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("SL:");

        spin_slChoose.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        spin_slChoose.setFocusable(false);
        spin_slChoose.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spin_slChooseStateChanged(evt);
            }
        });

        btn_ChooseSach.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_ChooseSach.setText("Chọn sách");
        btn_ChooseSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ChooseSachMouseClicked(evt);
            }
        });

        btn_lamMoi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_lamMoi.setText("Làm mới");
        btn_lamMoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btn_lamMoiMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_lamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spin_slChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(text_sachIndexClick))
                .addGap(18, 18, 18)
                .addComponent(btn_ChooseSach, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(spin_slChoose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_lamMoi))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(text_sachIndexClick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_ChooseSach, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("TỔNG TIỀN & GIẢM GIÁ"));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Tổng cộng:");

        text_TongCong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        text_TongCong.setText("0.0 đ");
        text_TongCong.setFocusable(false);

        radio_giamGia5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radio_giamGia5.setText("5%");
        radio_giamGia5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                radio_giamGia5MousePressed(evt);
            }
        });

        radio_giamGia10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radio_giamGia10.setText("10%");
        radio_giamGia10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                radio_giamGia10MousePressed(evt);
            }
        });

        radio_giamGia15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radio_giamGia15.setText("15%");
        radio_giamGia15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                radio_giamGia15MousePressed(evt);
            }
        });

        radio_giamGia20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radio_giamGia20.setText("20%");
        radio_giamGia20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                radio_giamGia20MousePressed(evt);
            }
        });

        radio_giamGia0.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radio_giamGia0.setSelected(true);
        radio_giamGia0.setText("0%");
        radio_giamGia0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                radio_giamGia0MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(text_TongCong, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(radio_giamGia0)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radio_giamGia5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radio_giamGia10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radio_giamGia15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radio_giamGia20)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radio_giamGia5)
                    .addComponent(radio_giamGia10)
                    .addComponent(radio_giamGia15)
                    .addComponent(radio_giamGia20)
                    .addComponent(radio_giamGia0))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(text_TongCong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(0, 102, 204));
        title.setText("HOÁ ĐƠN THỨ ...");

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("THÔNG TIN KHÁCH"));

        text_MaKhachMoi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setText("Mã khách hàng:");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setText("Tên khách hàng:");

        text_TenKhachMoi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setText("Địa chỉ:");

        textArea_diaChiKhachMoi.setColumns(20);
        textArea_diaChiKhachMoi.setRows(5);
        jScrollPane6.setViewportView(textArea_diaChiKhachMoi);

        radio_NamKhachMoi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radio_NamKhachMoi.setSelected(true);
        radio_NamKhachMoi.setText("Nam");
        radio_NamKhachMoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                radio_NamKhachMoiMousePressed(evt);
            }
        });

        radio_NuKhachMoi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        radio_NuKhachMoi.setText("Nữ");
        radio_NuKhachMoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                radio_NuKhachMoiMousePressed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setText("Số dt:");

        text_SdtKhachMoi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        text_SdtKhachMoi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                text_SdtKhachMoiKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(text_MaKhachMoi, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                            .addComponent(text_TenKhachMoi))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(radio_NamKhachMoi)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(radio_NuKhachMoi))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(text_SdtKhachMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane6))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(text_MaKhachMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radio_NamKhachMoi)
                    .addComponent(radio_NuKhachMoi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(text_TenKhachMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_SdtKhachMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(38, 38, 38))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(logo_left, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane1)
                            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(imagetopleft, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(imagetopright, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(imageLong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(imagetopleft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(imagetopright, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(logo_left, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(imageLong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this, "Bạn muốn quay lại trang chính ?", "Thông báo", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.OK_OPTION){
            this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            this.trangChu_GUI.setEnabled(true);
            return;
        }
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }//GEN-LAST:event_formWindowClosing

    private void radio_giamGia5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radio_giamGia5MousePressed
        // TODO add your handling code here:
        radio_giamGia0.setSelected(false);
        radio_giamGia10.setSelected(false);
        radio_giamGia15.setSelected(false);
        radio_giamGia20.setSelected(false);
        this.giamGia = radio_giamGia5.getText();
        DefaultTableModel tableModel = (DefaultTableModel)table_SachOrder.getModel();
        if(tableModel.getRowCount() > 0){
            this.loadGiamGia(tableModel, radio_giamGia5.getText());
            text_TongCong.setText(this.loadTongTien(tableModel) + " đ");
        }
        
    }//GEN-LAST:event_radio_giamGia5MousePressed

    private void radio_giamGia10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radio_giamGia10MousePressed
        // TODO add your handling code here:
        radio_giamGia0.setSelected(false);
        radio_giamGia5.setSelected(false);
        radio_giamGia15.setSelected(false);
        radio_giamGia20.setSelected(false);
        this.giamGia = radio_giamGia10.getText();
        DefaultTableModel tableModel = (DefaultTableModel)table_SachOrder.getModel();
        if(tableModel.getRowCount() > 0){
            this.loadGiamGia(tableModel, radio_giamGia10.getText());
            text_TongCong.setText(this.loadTongTien(tableModel) + " đ");
        }
        
    }//GEN-LAST:event_radio_giamGia10MousePressed

    private void radio_giamGia15MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radio_giamGia15MousePressed
        // TODO add your handling code here:
        radio_giamGia0.setSelected(false);
        radio_giamGia10.setSelected(false);
        radio_giamGia5.setSelected(false);
        radio_giamGia20.setSelected(false);
        this.giamGia = radio_giamGia15.getText();
        DefaultTableModel tableModel = (DefaultTableModel)table_SachOrder.getModel();
        if(tableModel.getRowCount() > 0){
            this.loadGiamGia(tableModel, radio_giamGia15.getText());
            text_TongCong.setText(this.loadTongTien(tableModel) + " đ");
        }
        
    }//GEN-LAST:event_radio_giamGia15MousePressed

    private void radio_giamGia20MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radio_giamGia20MousePressed
        // TODO add your handling code here:
        radio_giamGia0.setSelected(false);
        radio_giamGia10.setSelected(false);
        radio_giamGia15.setSelected(false);
        radio_giamGia5.setSelected(false);
        this.giamGia = radio_giamGia20.getText();
        DefaultTableModel tableModel = (DefaultTableModel)table_SachOrder.getModel();
        if(tableModel.getRowCount() > 0){
            this.loadGiamGia(tableModel, radio_giamGia20.getText());
            text_TongCong.setText(this.loadTongTien(tableModel) + " đ");
        }
        
    }//GEN-LAST:event_radio_giamGia20MousePressed

    private void radio_NamKhachMoiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radio_NamKhachMoiMousePressed
        // TODO add your handling code here:
        radio_NuKhachMoi.setSelected(false);
    }//GEN-LAST:event_radio_NamKhachMoiMousePressed

    private void radio_NuKhachMoiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radio_NuKhachMoiMousePressed
        // TODO add your handling code here:
        radio_NamKhachMoi.setSelected(false);
    }//GEN-LAST:event_radio_NuKhachMoiMousePressed

    private void spin_slSachOrderTrStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spin_slSachOrderTrStateChanged
        // TODO add your handling code here:
        String valueSpin = spin_slSachOrderTr.getValue().toString();
      
        if(Integer.parseInt(valueSpin) < 1){
            spin_slSachOrderTr.setValue(1);
        }
        else{
            if(!text_slSachOrder.getText().equals("")){
                int slOrder = Integer.parseInt(text_slSachOrder.getText());
                if(Integer.parseInt(valueSpin) > slOrder){
                    spin_slSachOrderTr.setValue(slOrder);
                }
            }
            else{
                spin_slSachOrderTr.setValue(1);
            }
        }
    }//GEN-LAST:event_spin_slSachOrderTrStateChanged

    private void loadGiamGia(DefaultTableModel tableModel, String giamGia){
        double giam = Double.parseDouble(giamGia.split("%")[0]) / 100;
        for(int i = 0; i < tableModel.getRowCount(); i++){
            int sl = Integer.parseInt(tableModel.getValueAt(i, 2).toString());
            double gia = Double.parseDouble(tableModel.getValueAt(i, 1).toString());
            double tien = gia * sl;
            double thanhTien = tien - tien * giam;
            tableModel.setValueAt(thanhTien, i, 3);
        }
    }
    
    private void spin_slChooseStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spin_slChooseStateChanged
        // TODO add your handling code here:
        String valueSpin = spin_slChoose.getValue().toString();
        if(Integer.parseInt(valueSpin) < 1){
            spin_slChoose.setValue(1);
        }
        else{
            if(Integer.parseInt(valueSpin) > this.soLuongTrongKho){
                spin_slChoose.setValue(this.soLuongTrongKho);
            }
        }
    }//GEN-LAST:event_spin_slChooseStateChanged

    private void table_SachChooseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_SachChooseMousePressed
        // TODO add your handling code here:
        if(table_SachChoose.getSelectedRowCount() == 1){
            int numRow = table_SachChoose.getSelectedRow();
            
            String tenSach = table_SachChoose.getValueAt(numRow, 0).toString();
            String soLuong = table_SachChoose.getValueAt(numRow, 3).toString();
            
            text_sachIndexClick.setText(tenSach);
            this.soLuongTrongKho = Integer.parseInt(soLuong);
        }
    }//GEN-LAST:event_table_SachChooseMousePressed

    private void btn_ChooseSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ChooseSachMouseClicked
        // TODO add your handling code here:
        if(text_sachIndexClick.getText().equals("")){
            return;
        }
        
        DefaultTableModel tableModelOrder = (DefaultTableModel)table_SachOrder.getModel();
        DefaultTableModel tableModelChoose = (DefaultTableModel)table_SachChoose.getModel();
        
        int numRow = table_SachChoose.getSelectedRow();
        int countRowTableOrder = table_SachOrder.getRowCount();
        if(this.congThemSachTonTai(tableModelOrder, tableModelChoose, numRow, countRowTableOrder) == true){
//                System.out.print("\n" + this.slChoose);
            this.loadgiamGiaAfter(tableModelOrder);
            this.l_sachChoose = updatel_sachChoose(tableModelChoose);
            return;
        }
        
        this.themMoiSach(tableModelOrder, tableModelChoose, numRow);     
        this.loadgiamGiaAfter(tableModelOrder);
        this.l_sachChoose = updatel_sachChoose(tableModelChoose);
    }//GEN-LAST:event_btn_ChooseSachMouseClicked
    
    private double loadTongTien(DefaultTableModel tableOrder){
        double tongTien = 0;
        for(int i = 0; i < tableOrder.getRowCount(); i++){
            double thanhTien = Double.parseDouble(tableOrder.getValueAt(i, 3).toString());
            tongTien += thanhTien;
        }
        return tongTien;
    }
    
    private boolean congThemSachTonTai(DefaultTableModel tableModelOrder, DefaultTableModel tableModelChoose, int numRow, int countRowTableOrder){

        for(int i = 0; i < countRowTableOrder; i++){
            String tenSach = table_SachOrder.getValueAt(i, 0).toString();
            if(tenSach.equals(text_sachIndexClick.getText())){
                
                int slOrder = Integer.parseInt(table_SachOrder.getValueAt(i, 2).toString());
                int valueSpinChoose = Integer.parseInt(spin_slChoose.getValue().toString());
                int sl = slOrder + valueSpinChoose;
                table_SachOrder.setValueAt(sl, i, 2);
                double gia = Double.parseDouble(table_SachOrder.getValueAt(i, 1).toString());
                double thanhTien = gia * sl;
                tableModelOrder.setValueAt(thanhTien, i, 3);

                int slSelectedRow = Integer.parseInt(table_SachChoose.getValueAt(numRow, 3).toString());
                int updateSl = slSelectedRow - valueSpinChoose;
                this.slChoose = updateSl;
                if(updateSl == 0){
                    this.soLuongTrongKho = 1;
                    text_sachIndexClick.setText("");
                    tableModelChoose.removeRow(numRow);
                }
                else{
                    this.soLuongTrongKho = updateSl;
                    table_SachChoose.setValueAt(updateSl, numRow, 3);
                }
                this.loadSlSachOrder();
                spin_slChoose.setValue(1);
                return true;
            }
        }     
        return false;
    }
    
    private void loadSlSachOrder(){
        if(table_SachOrder.getSelectedRowCount() == 1){
            int numRow = table_SachOrder.getSelectedRow();
            int countSach = Integer.valueOf(table_SachOrder.getValueAt(numRow, 2).toString());
            text_slSachOrder.setText(String.valueOf(countSach));
            spin_slSachOrderTr.setValue(1);
        }
    }
    
    private void themMoiSach(DefaultTableModel tableModelOrder, DefaultTableModel tableModelChoose, int numRow){
        
        int slChoose = Integer.parseInt(spin_slChoose.getValue().toString());
        double gia = Double.parseDouble(table_SachChoose.getValueAt(numRow, 2).toString());
        double thanhTien = gia * slChoose;
        tableModelOrder.addRow(new String[]{
            table_SachChoose.getValueAt(numRow, 0).toString(),
            String.valueOf(gia),
            String.valueOf(slChoose),
            String.valueOf(thanhTien),
            table_SachChoose.getValueAt(numRow, 1).toString(),
            table_SachChoose.getValueAt(numRow, 4).toString(),
            table_SachChoose.getValueAt(numRow, 5).toString()
        });
       
        int slSelectedRow = Integer.parseInt(table_SachChoose.getValueAt(numRow, 3).toString());
        int updateSl = slSelectedRow - slChoose;
        
        table_SachChoose.setValueAt(updateSl, numRow, 3);
        
        if(updateSl == 0){
            this.soLuongTrongKho = 1;
            text_sachIndexClick.setText("");
            tableModelChoose.removeRow(numRow);
        }
        else{
            this.soLuongTrongKho = updateSl;
            table_SachChoose.setValueAt(updateSl, numRow, 3);
        }
        spin_slChoose.setValue(1);
    }
    
    private void table_SachOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_SachOrderMouseClicked
        // TODO add your handling code here:
        this.loadSlSachOrder();
    }//GEN-LAST:event_table_SachOrderMouseClicked

    
    private boolean xoaBotSlOrder(DefaultTableModel tableModelOrder, DefaultTableModel tableModelChoose, int numSlTru, int slOrder, int numRow){
        
        String tenSach = table_SachOrder.getValueAt(numRow, 0).toString();
        for(int i = 0; i < table_SachChoose.getRowCount(); i++){
            String tenSachChoose = table_SachChoose.getValueAt(i, 0).toString();
            if(tenSachChoose.equals(tenSach)){
                int slTonKho = Integer.parseInt(tableModelChoose.getValueAt(i, 3).toString());
                
                if(numSlTru == slOrder){
                    tableModelOrder.removeRow(numRow);
                    tableModelChoose.setValueAt((slTonKho + numSlTru), i, 3);
                    spin_slSachOrderTr.setValue(1);
                    text_slSachOrder.setText("");
                    return true;
                }
                else{
                    int slConLai = slOrder - numSlTru;
                    tableModelOrder.setValueAt(slConLai, numRow, 2); 
                    double gia = Double.parseDouble(table_SachOrder.getValueAt(numRow, 1).toString());
                    double thanhTien = gia * slConLai;
                    tableModelOrder.setValueAt(thanhTien, numRow, 3);
                    tableModelChoose.setValueAt((slTonKho + numSlTru), i, 3);
                    this.loadSlSachOrder();
                    return true;
                }
            }
        }
        return false;
    }
    
    private void xoaOrderEmptyChoose(DefaultTableModel tableModelOrder, DefaultTableModel tableModelChoose, int numSlTru, int slOrder, int numRow){
            int slHienTai = Integer.parseInt(tableModelOrder.getValueAt(numRow, 2).toString());
            int slTru = Integer.parseInt(spin_slSachOrderTr.getValue().toString());
            int slConLai = slOrder - numSlTru;
            tableModelOrder.setValueAt(slConLai, numRow, 2); 
            double gia = Double.parseDouble(table_SachOrder.getValueAt(numRow, 1).toString());
            double thanhTien = gia * slConLai;
            String resultSl = null;
            this.loadSlSachOrder();
            if(slConLai == 0){
                resultSl = String.valueOf(slHienTai);
            }
            else{
                resultSl = String.valueOf(slTru);
                tableModelOrder.setValueAt(slConLai, numRow, 2);
                tableModelOrder.setValueAt(thanhTien, numRow, 3);
            }
            tableModelChoose.addRow(new String[]{
                tableModelOrder.getValueAt(numRow, 0).toString(),
                tableModelOrder.getValueAt(numRow, 4).toString(),
                tableModelOrder.getValueAt(numRow, 1).toString(),
                resultSl,
                tableModelOrder.getValueAt(numRow, 5).toString(),
                tableModelOrder.getValueAt(numRow, 6).toString()
            });
            if(slConLai == 0){
                tableModelOrder.removeRow(numRow);   
            }
            spin_slSachOrderTr.setValue(1);
            text_slSachOrder.setText("");
    }
   
    private void loadgiamGiaAfter(DefaultTableModel tableModel){
        if(radio_giamGia5.isSelected()){
            this.loadGiamGia(tableModel, radio_giamGia5.getText());
            text_TongCong.setText(this.loadTongTien(tableModel) + " đ");
        }
        else if(radio_giamGia10.isSelected()){
            this.loadGiamGia(tableModel, radio_giamGia10.getText());
            text_TongCong.setText(this.loadTongTien(tableModel) + " đ");
        }
        else if(radio_giamGia15.isSelected()){
            this.loadGiamGia(tableModel, radio_giamGia15.getText());
            text_TongCong.setText(this.loadTongTien(tableModel) + " đ");
        }
        else if(radio_giamGia20.isSelected()){
            this.loadGiamGia(tableModel, radio_giamGia20.getText());
            text_TongCong.setText(this.loadTongTien(tableModel) + " đ");
        }
        else{
            this.loadGiamGia(tableModel, radio_giamGia0.getText());
            text_TongCong.setText(this.loadTongTien(tableModel) + " đ");
        }
    }
    
    private void btn_XoaInOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_XoaInOrderMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tableModelOrder = (DefaultTableModel)table_SachOrder.getModel();
        DefaultTableModel tableModelChoose = (DefaultTableModel)table_SachChoose.getModel();
                    
        int numSlTru = Integer.parseInt(spin_slSachOrderTr.getValue().toString());
        int slOrder = Integer.parseInt(text_slSachOrder.getText());
        int numRow = table_SachOrder.getSelectedRow();
            
        if(this.xoaBotSlOrder(tableModelOrder, tableModelChoose, numSlTru, slOrder, numRow) == true){
     
            this.loadgiamGiaAfter(tableModelOrder);
            this.l_sachChoose = this.updatel_sachChoose(tableModelOrder);
            return;
        }
        
        this.xoaOrderEmptyChoose(tableModelOrder, tableModelChoose, numSlTru, slOrder, numRow);
        this.loadgiamGiaAfter(tableModelOrder);
        this.l_sachChoose = this.updatel_sachChoose(tableModelOrder);
    }//GEN-LAST:event_btn_XoaInOrderMouseClicked

    private void spin_slSachOrderTrKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_spin_slSachOrderTrKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_spin_slSachOrderTrKeyReleased

    private void radio_giamGia0MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radio_giamGia0MousePressed
        // TODO add your handling code here:
        radio_giamGia10.setSelected(false);
        radio_giamGia5.setSelected(false);
        radio_giamGia15.setSelected(false);
        radio_giamGia20.setSelected(false);
        this.giamGia = radio_giamGia0.getText();
        DefaultTableModel tableModel = (DefaultTableModel)table_SachOrder.getModel();
        if(tableModel.getRowCount() > 0){
            this.loadGiamGia(tableModel, radio_giamGia0.getText());
            text_TongCong.setText(this.loadTongTien(tableModel) + " đ");
        }
        
    }//GEN-LAST:event_radio_giamGia0MousePressed

    private ArrayList<JTextField> listText(){
        ArrayList<JTextField> list_t = new ArrayList<JTextField>();
        list_t.add(text_MaKhachMoi);
        list_t.add(text_SdtKhachMoi);
        list_t.add(text_TenKhachMoi);
        list_t.add(text_TongCong);
        list_t.add(text_sachIndexClick);
        list_t.add(text_slSachOrder);
        return list_t;
    }
    
    private void btn_lamMoiMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lamMoiMouseReleased
        // TODO add your handling code here:
        ArrayList<JTextField> list_t = this.listText();
        for(JTextField text : list_t){
            text.setText("");
        }
        
        textArea_diaChiKhachMoi.setText("");
        this.loadSlSachOrder();
        radio_giamGia0.setSelected(true);
        radio_giamGia10.setSelected(false);
        radio_giamGia15.setSelected(false);
        radio_giamGia20.setSelected(false);
        radio_giamGia20.setSelected(false);
        radio_NamKhachMoi.setSelected(true);
        radio_NuKhachMoi.setSelected(false);

        spin_slChoose.setValue(1);
        spin_slSachOrderTr.setValue(1);
        this.soLuongTrongKho = 1;
        this.loadTableChoose();
        ((DefaultTableModel)table_SachOrder.getModel()).setRowCount(0);
        
    }//GEN-LAST:event_btn_lamMoiMouseReleased

    private void btn_ThanhToanMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ThanhToanMouseReleased
        // TODO add your handling code here:
        
        String tenKhach = text_TenKhachMoi.getText();
        String sdtKhach = text_SdtKhachMoi.getText();
        String maKhach = text_MaKhachMoi.getText();
        String dchiKhach = textArea_diaChiKhachMoi.getText();
        DefaultTableModel tableModel = (DefaultTableModel)table_SachOrder.getModel();
        if(tenKhach.equals("") || sdtKhach.equals("") || maKhach.equals("") || dchiKhach.equals("")){
            JOptionPane.showConfirmDialog(this, "Nhập đầy đủ thông để tiến hành thanh toán !!!", "Thông báo", JOptionPane.CLOSED_OPTION, JOptionPane.WARNING_MESSAGE);
        }
        else if(tableModel.getRowCount() == 0){
            JOptionPane.showConfirmDialog(this, "Nhập sách cho khách để tiến hành thanh toán !!!", "Thông báo", JOptionPane.CLOSED_OPTION, JOptionPane.WARNING_MESSAGE);
        }
        else{
            String maKH = text_MaKhachMoi.getText();
            String tenKH = text_TenKhachMoi.getText();
            String sdtKH = text_SdtKhachMoi.getText();
            String diachiKH = textArea_diaChiKhachMoi.getText();
            String gtKH = "Nam";
            if(radio_NamKhachMoi.isSelected()){
                gtKH = radio_NamKhachMoi.getText();
            }
            else{
                if(radio_NuKhachMoi.isSelected()){
                    gtKH = radio_NuKhachMoi.getText();
                }
            }
            
            if(KhachHang_DAO.getKhachQuen(maKH).equals("0")){
                int result = KhachHang_DAO.addNewKhachHang(maKH, tenKH, sdtKH, gtKH, diachiKH);
                if(result <= 0){
                    JOptionPane.showConfirmDialog(this, "Xảy ra lỗi thêm khách hàng !!!", "Thông báo", JOptionPane.CLOSED_OPTION, JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
                   
            String ngayThanhToan = new SimpleDateFormat("yyyy-MM-dd").format(Date.from(Instant.now()));
            int result = HoaDon_DAO.addNewHoaDon(maKH, this.maNV, ngayThanhToan);
            if(result <= 0){
                JOptionPane.showConfirmDialog(this, "Xảy ra lỗi thêm hoá đơn !!!", "Thông báo", JOptionPane.CLOSED_OPTION, JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            String maHD = HoaDon_DAO.getMaHD();
            int resultAddOrder = 0;
            int numRow = table_SachOrder.getRowCount();
            for(int i = 0; i < numRow; i++){
                String tenSach = table_SachOrder.getValueAt(i, 0).toString();
                String maCT_HD = maHD;
                String maSach = Sach_DAO.getMaSach(tenSach);
                String sl = table_SachOrder.getValueAt(i, 2).toString();
                String giamGia = this.giamGia;
                String thanhTien = table_SachOrder.getValueAt(i, 3).toString();
                
                result = CT_HoaDon_DAO.addNewCT_HoaDon(maCT_HD, maSach, sl, giamGia, thanhTien);
               
                if(result <= 0){
                    System.err.print("\nKhông thể thêm món hàng mã " + maSach);
                }
                else{
                    resultAddOrder++;
                }
            }
            
            if(resultAddOrder == numRow){
                JOptionPane.showConfirmDialog(this, "Thanh toán thành công đơn hàng HD" + maHD, "Thông báo", JOptionPane.CLOSED_OPTION, JOptionPane.INFORMATION_MESSAGE);             
            }
            else{
                JOptionPane.showConfirmDialog(this, "Xảy ra lỗi thanh toán đơn hàng HD" + maHD, "Thông báo", JOptionPane.CLOSED_OPTION, JOptionPane.ERROR_MESSAGE);             
            }
        }
    }//GEN-LAST:event_btn_ThanhToanMouseReleased

    private void text_SdtKhachMoiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_SdtKhachMoiKeyPressed
        // TODO add your handling code here:
        if(Character.isLetter(evt.getKeyChar()) && evt.getKeyChar() != KeyEvent.VK_BACK_SPACE || text_SdtKhachMoi.getText().length() == 11){
            text_SdtKhachMoi.setEditable(false);
            return;
        }
        text_SdtKhachMoi.setEditable(true);
    }//GEN-LAST:event_text_SdtKhachMoiKeyPressed

    private void addColumnTableSachChoose(){
        DefaultTableModel tableModel = (DefaultTableModel)table_SachChoose.getModel();
        tableModel.setColumnIdentifiers(new String[]{
            "Tên sách", "Thể loại", "Giá", "Sl trong kho", "Tác giả", "Ngày xuất bản"
        });
        
        DefaultTableColumnModel tableColumnModel = (DefaultTableColumnModel)table_SachChoose.getColumnModel();
        tableColumnModel.getColumn(0).setPreferredWidth(250);
        tableColumnModel.getColumn(1).setPreferredWidth(100);
        tableColumnModel.getColumn(2).setPreferredWidth(130);
        tableColumnModel.getColumn(3).setPreferredWidth(130);
        tableColumnModel.getColumn(4).setPreferredWidth(130);
        tableColumnModel.getColumn(5).setPreferredWidth(120);
        
        table_SachChoose.getTableHeader().setFont(new Font("Arial", Font.BOLD, 15));
        
    }
    
    private void addColumnTableSachOrder(){
        DefaultTableModel tableModel = (DefaultTableModel)table_SachOrder.getModel();
        tableModel.setColumnIdentifiers(new String[]{
            "Tên sách", "Giá", "Số lượng", "Thành tiền", "Thể loại", "Tác giả", "Ngày xuất bản"
        });
        
        DefaultTableColumnModel tableColumnModel = (DefaultTableColumnModel)table_SachOrder.getColumnModel();
        tableColumnModel.getColumn(0).setPreferredWidth(250);
        tableColumnModel.getColumn(1).setPreferredWidth(100);
        tableColumnModel.getColumn(2).setPreferredWidth(100);
        tableColumnModel.getColumn(3).setPreferredWidth(120);
        tableColumnModel.getColumn(4).setPreferredWidth(120);
        tableColumnModel.getColumn(5).setPreferredWidth(120);
        tableColumnModel.getColumn(6).setPreferredWidth(120);
        
        table_SachOrder.getTableHeader().setFont(new Font("Arial", Font.BOLD, 15));
        
        tableModel.setRowCount(0);
    }
    
    private void loadTableChoose(){
        this.addColumnTableSachChoose();
        
        DefaultTableModel tableModel = (DefaultTableModel)table_SachChoose.getModel();
        tableModel.setRowCount(0);
        
        this.l_sachs = Sach_DAO.getListSach();
        
        for(Sach_DTO sach : this.l_sachs){
            tableModel.addRow(new String[]{
                sach.getTenSach(),
                sach.getTheLoai(),
                String.valueOf(sach.getGia()),
                String.valueOf(sach.getSoLuong()),
                sach.getTacGia(),
                new SimpleDateFormat("dd/MM/yyyy").format(sach.getNgayXuatBan())
            });
        }
        
        this.l_sachChoose = this.updatel_sachChoose(tableModel);
    }
    
    private ArrayList<String[]> updatel_sachChoose(DefaultTableModel tableModel){
        ArrayList<String[]> listSachs = new ArrayList<String[]>();
        for(int i = 0; i < tableModel.getRowCount(); i++){
            listSachs.add(new String[]{
                tableModel.getValueAt(i, 0).toString(),
                tableModel.getValueAt(i, 1).toString(),
                tableModel.getValueAt(i, 2).toString(),
                tableModel.getValueAt(i, 3).toString(),
                tableModel.getValueAt(i, 4).toString(),
                tableModel.getValueAt(i, 5).toString()
            });
        }
        
        return listSachs;
    }
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ChooseSach;
    private javax.swing.JButton btn_ThanhToan;
    private javax.swing.JButton btn_XoaInOrder;
    private javax.swing.JButton btn_lamMoi;
    private javax.swing.JLabel imageLong;
    private javax.swing.JLabel imagetopleft;
    private javax.swing.JLabel imagetopright;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel logo_left;
    private javax.swing.JRadioButton radio_NamKhachMoi;
    private javax.swing.JRadioButton radio_NuKhachMoi;
    private javax.swing.JRadioButton radio_giamGia0;
    private javax.swing.JRadioButton radio_giamGia10;
    private javax.swing.JRadioButton radio_giamGia15;
    private javax.swing.JRadioButton radio_giamGia20;
    private javax.swing.JRadioButton radio_giamGia5;
    private javax.swing.JSpinner spin_slChoose;
    private javax.swing.JSpinner spin_slSachOrderTr;
    private javax.swing.JTable table_SachChoose;
    private javax.swing.JTable table_SachOrder;
    private javax.swing.JTextArea textArea_diaChiKhachMoi;
    private javax.swing.JTextField text_MaKhachMoi;
    private javax.swing.JTextField text_SdtKhachMoi;
    private javax.swing.JTextField text_TenKhachMoi;
    private javax.swing.JTextField text_TongCong;
    private javax.swing.JTextField text_sachIndexClick;
    private javax.swing.JTextField text_slSachOrder;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
