/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.TheLoai_DAO;
import DTO.TheLoai_DTO;
import java.awt.Font;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nguye
 */
public class TheLoai_GUI extends javax.swing.JFrame {
    private Sach_GUI sach_GUI = null;
    private String Quyen = null;
    private ArrayList<TheLoai_DTO> l_theLoais = null;

    /**
     * Creates new form TheLoai_GUI
     */
    public TheLoai_GUI(Sach_GUI sach_GUI, String Quyen) {
        this.sach_GUI = sach_GUI;
        this.Quyen = Quyen;
        initComponents();
        this.setTitle("Thể loại sách");
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        
        if(!this.Quyen.equals("Admin")){
            btn_ThemTheLoai.setEnabled(false);
        }
        
        this.loadTableTheLoai();
        
        title.setHorizontalAlignment(SwingConstants.CENTER);
        title.setHorizontalTextPosition(SwingConstants.CENTER);
        
        ImageIcon imageIcon = new ImageIcon("src/Pictures/imgTheLoaiSach.jpg");
        Image image = imageIcon.getImage().getScaledInstance(imgTheLoaiSach.getWidth(), imgTheLoaiSach.getHeight(), Image.SCALE_SMOOTH);
        imgTheLoaiSach.setIcon(new ImageIcon(image));
    }
    
    
    private void addColumnTableTheLoai(){
        DefaultTableModel tableModel = (DefaultTableModel)table_theLoaiSach.getModel();
        
        tableModel.setColumnIdentifiers(new String[]{
            "Mã thể loại", "Thể loại"
        });
        
        DefaultTableColumnModel tableColumnModel = (DefaultTableColumnModel)table_theLoaiSach.getColumnModel();
        tableColumnModel.getColumn(0).setPreferredWidth(200);
        tableColumnModel.getColumn(1).setPreferredWidth(200);
        
        table_theLoaiSach.getTableHeader().setFont(new Font("Arial", Font.BOLD, 15));
    }
    
    private void loadTableTheLoai(){
        this.addColumnTableTheLoai();
        
        DefaultTableModel tableModel = (DefaultTableModel)table_theLoaiSach.getModel();
        tableModel.setRowCount(0);
        this.l_theLoais = TheLoai_DAO.getListTheLoai();
        
        for(TheLoai_DTO item : this.l_theLoais){
            tableModel.addRow(new String[]{
                item.getMa_TL(),
                item.getTl_Sach()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        text_maTL = new javax.swing.JTextField();
        btn_ThemTheLoai = new javax.swing.JButton();
        text_searchTheLoai = new javax.swing.JTextField();
        text_TL = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_sua = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_lamMoi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_theLoaiSach = new javax.swing.JTable();
        imgTheLoaiSach = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(0, 102, 204));
        title.setText("THỂ LOẠI SÁCH");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("THÊM MỚI & TÌM KIẾM"));

        text_maTL.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btn_ThemTheLoai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_ThemTheLoai.setText("Thêm thể loại");
        btn_ThemTheLoai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ThemTheLoaiMouseClicked(evt);
            }
        });

        text_searchTheLoai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        text_searchTheLoai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                text_searchTheLoaiKeyReleased(evt);
            }
        });

        text_TL.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Mã thể loại:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Thể loại:");

        btn_sua.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_sua.setText("Sửa");
        btn_sua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_suaMouseClicked(evt);
            }
        });

        btn_xoa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_xoa.setText("Xoá");
        btn_xoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_xoaMouseClicked(evt);
            }
        });

        btn_lamMoi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_lamMoi.setText("Làm mới");
        btn_lamMoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_lamMoiMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(text_searchTheLoai)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(text_maTL, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                            .addComponent(text_TL))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btn_sua)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_xoa))
                        .addComponent(btn_ThemTheLoai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btn_lamMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(text_maTL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addComponent(btn_ThemTheLoai))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_TL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btn_sua)
                    .addComponent(btn_xoa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_searchTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_lamMoi))
                .addContainerGap())
        );

        table_theLoaiSach.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        table_theLoaiSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        table_theLoaiSach.setRowHeight(20);
        table_theLoaiSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_theLoaiSachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_theLoaiSach);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                    .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imgTheLoaiSach, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(imgTheLoaiSach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this, "Bạn muốn quay lại trang sách ?", "Thông báo", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.OK_OPTION){
            this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            this.sach_GUI.reSetALL();
            return;
        }
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }//GEN-LAST:event_formWindowClosing

    private void table_theLoaiSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_theLoaiSachMouseClicked
        // TODO add your handling code here:
        text_maTL.setFocusable(false);
        if(table_theLoaiSach.getSelectedRowCount() == 1){
            int numRow = table_theLoaiSach.getSelectedRow();
            text_maTL.setText(table_theLoaiSach.getValueAt(numRow, 0).toString());
            text_TL.setText(table_theLoaiSach.getValueAt(numRow, 1).toString());
        }
    }//GEN-LAST:event_table_theLoaiSachMouseClicked

    private void btn_lamMoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lamMoiMouseClicked
        // TODO add your handling code here:
        text_maTL.setText("");
        text_maTL.setFocusable(true);
        text_TL.setText("");
        text_searchTheLoai.setText("");
    }//GEN-LAST:event_btn_lamMoiMouseClicked

    private void btn_ThemTheLoaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ThemTheLoaiMouseClicked
        // TODO add your handling code here:
        if(text_maTL.getText().equals("") || text_TL.getText().equals("")){
            JOptionPane.showConfirmDialog(this, "Hãy nhập đầy đủ dữ liệu", "Thông báo", JOptionPane.CLOSED_OPTION, JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if(JOptionPane.showConfirmDialog(this, "Thêm mới thể loại ?", "Thông báo", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.OK_OPTION){
            int result = TheLoai_DAO.addNewTheLoai(text_maTL.getText(), text_TL.getText());
            this.loadTableTheLoai();
            if(result <= 0){
                JOptionPane.showConfirmDialog(this, "Có vẻ như xảy ra lỗi !!!", "Thông báo", JOptionPane.CLOSED_OPTION, JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_ThemTheLoaiMouseClicked

    private void btn_suaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_suaMouseClicked
        // TODO add your handling code here:
        if(table_theLoaiSach.getSelectedRowCount() == 1){
            if(JOptionPane.showConfirmDialog(this, "Đồng ý sửa thể lại này ?", "Thông báo", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.OK_OPTION){
                int result = TheLoai_DAO.updateTheLoai(text_maTL.getText(), text_TL.getText());
                this.loadTableTheLoai();
                
                if(result <= 0){
                    JOptionPane.showConfirmDialog(this, "Có vẻ như xảy ra lỗi !!!", "Thông báo", JOptionPane.CLOSED_OPTION, JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        else{
            JOptionPane.showConfirmDialog(this, "Hãy chọn thể loại muốn sửa", "Thông báo", JOptionPane.CLOSED_OPTION, JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btn_suaMouseClicked

    private void btn_xoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_xoaMouseClicked
        // TODO add your handling code here:
        if(table_theLoaiSach.getSelectedRowCount() == 1){
            if(JOptionPane.showConfirmDialog(this, "Đồng ý xoá thể lại này ?", "Thông báo", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.OK_OPTION){
                int result = TheLoai_DAO.deleteTheloai(text_maTL.getText());
                this.loadTableTheLoai();
                
                if(result <= 0){
                    JOptionPane.showConfirmDialog(this, "Có vẻ như xảy ra lỗi !!!", "Thông báo", JOptionPane.CLOSED_OPTION, JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        else{
            JOptionPane.showConfirmDialog(this, "Hãy chọn thể loại muốn xoá", "Thông báo", JOptionPane.CLOSED_OPTION, JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btn_xoaMouseClicked

    private void text_searchTheLoaiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_searchTheLoaiKeyReleased
        // TODO add your handling code here:
        DefaultTableModel tableModel = (DefaultTableModel)table_theLoaiSach.getModel();
        
        tableModel.setRowCount(0);
        
        for(TheLoai_DTO item : this.l_theLoais){
            if(item.getTl_Sach().contains(text_searchTheLoai.getText())){
                tableModel.addRow(new String[]{
                    item.getMa_TL(),
                    item.getTl_Sach()
                });
            }
        }    
    }//GEN-LAST:event_text_searchTheLoaiKeyReleased

  
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ThemTheLoai;
    private javax.swing.JButton btn_lamMoi;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JLabel imgTheLoaiSach;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_theLoaiSach;
    private javax.swing.JTextField text_TL;
    private javax.swing.JTextField text_maTL;
    private javax.swing.JTextField text_searchTheLoai;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
