/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author nguye
 */
public class TrangChu_GUI extends javax.swing.JFrame {
    private String Ma_NV = null;
    private String Quyen = null;
    private DangNhap_GUI dangNhap_GUI = null;
    /**
     * Creates new form TrangChu
     */
    public TrangChu_GUI(DangNhap_GUI dangNhap_GUI, String Ma_NV, String Quyen) {
        this.Ma_NV = Ma_NV;
        this.Quyen = Quyen;
        this.dangNhap_GUI = dangNhap_GUI;
        initComponents();
        this.setTitle("Trang chủ nhân viên");
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        
        if(!this.Quyen.equals("Admin")){
            btn_DanhSachNV.setVisible(false);
        }
        
        
        ImageIcon imageicon = new ImageIcon("src/Pictures/imgTrangChu.jpg");
        Image image = imageicon.getImage().getScaledInstance(ImageHome.getWidth(), ImageHome.getHeight(), Image.SCALE_SMOOTH);
        ImageHome.setIcon(new ImageIcon(image));
        
        imageicon = new ImageIcon("src/Pictures/logoStoreHome.png");
        image = imageicon.getImage().getScaledInstance(ImageLogo.getWidth(), ImageLogo.getHeight(), Image.SCALE_SMOOTH);
        ImageLogo.setIcon(new ImageIcon(image));
        
        imageicon = new ImageIcon("src/Pictures/Profile.jpg");
        image = imageicon.getImage().getScaledInstance(ImageProfile.getWidth(), ImageProfile.getHeight(), Image.SCALE_SMOOTH);
        ImageProfile.setIcon(new ImageIcon(image));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        btn_QuanLySach = new javax.swing.JButton();
        btn_QuanLyHoaDon = new javax.swing.JButton();
        btn_QuanLyKhachHang = new javax.swing.JButton();
        btn_TaoHoaDon = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btn_ThongTin = new javax.swing.JButton();
        btn_DanhSachNV = new javax.swing.JButton();
        ImageHome = new javax.swing.JLabel();
        ImageLogo = new javax.swing.JLabel();
        ImageProfile = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuHome = new javax.swing.JMenu();
        menuItemDoiMatKhau = new javax.swing.JMenuItem();
        menuItemDangXuat = new javax.swing.JMenuItem();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("LỰA CHỌN CHÍNH"));

        btn_QuanLySach.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_QuanLySach.setText("Quản lý sách");
        btn_QuanLySach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_QuanLySachMouseClicked(evt);
            }
        });

        btn_QuanLyHoaDon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_QuanLyHoaDon.setText("Quản lý hoá đơn");
        btn_QuanLyHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_QuanLyHoaDonMouseClicked(evt);
            }
        });

        btn_QuanLyKhachHang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_QuanLyKhachHang.setText("Quản lý khách hàng");
        btn_QuanLyKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_QuanLyKhachHangMouseClicked(evt);
            }
        });

        btn_TaoHoaDon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_TaoHoaDon.setText("Tạo hoá đơn");
        btn_TaoHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_TaoHoaDonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_QuanLySach, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_QuanLyHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_QuanLyKhachHang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_TaoHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_QuanLyHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(btn_QuanLySach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_QuanLyKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_TaoHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );

        btn_ThongTin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_ThongTin.setText("Thông tin của tôi");
        btn_ThongTin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ThongTinMouseClicked(evt);
            }
        });

        btn_DanhSachNV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_DanhSachNV.setText("Danh sách nhân viên");
        btn_DanhSachNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_DanhSachNVMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_ThongTin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_DanhSachNV, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_ThongTin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_DanhSachNV, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );

        menuHome.setText("Tuỳ chọn");

        menuItemDoiMatKhau.setText("Đổi mật khẩu");
        menuItemDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemDoiMatKhauActionPerformed(evt);
            }
        });
        menuHome.add(menuItemDoiMatKhau);

        menuItemDangXuat.setText("Đăng xuất");
        menuItemDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemDangXuatActionPerformed(evt);
            }
        });
        menuHome.add(menuItemDangXuat);

        jMenuBar1.add(menuHome);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ImageHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ImageLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ImageProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ImageLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ImageProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 83, Short.MAX_VALUE))
                    .addComponent(ImageHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this, "Bạn muốn thoát ?", "Thông báo", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.OK_OPTION){
            this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            this.dangNhap_GUI.setVisible(true);
            this.dangNhap_GUI.setText_passwordNull();
            return;
        }
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }//GEN-LAST:event_formWindowClosing

    private void btn_QuanLySachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_QuanLySachMouseClicked
        // TODO add your handling code here:
        new Sach_GUI(this, this.Quyen);
        this.setEnabled(false);
    }//GEN-LAST:event_btn_QuanLySachMouseClicked

    private void btn_QuanLyHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_QuanLyHoaDonMouseClicked
        // TODO add your handling code here:
        new HoaDon_GUI(this);
        this.setEnabled(false);
    }//GEN-LAST:event_btn_QuanLyHoaDonMouseClicked

    private void btn_QuanLyKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_QuanLyKhachHangMouseClicked
        // TODO add your handling code here:
        new KhachHang_GUI(this, this.Quyen);
        this.setEnabled(false);
    }//GEN-LAST:event_btn_QuanLyKhachHangMouseClicked

    private void btn_DanhSachNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DanhSachNVMouseClicked
        // TODO add your handling code here:
        new NhanVien_GUI(this, this.Ma_NV);
        this.setEnabled(false);
    }//GEN-LAST:event_btn_DanhSachNVMouseClicked

    private void btn_ThongTinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ThongTinMouseClicked
        // TODO add your handling code here:
        new ThongTinNV_GUI(this, this.Ma_NV);
        this.setEnabled(false);
    }//GEN-LAST:event_btn_ThongTinMouseClicked

    private void btn_TaoHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_TaoHoaDonMouseClicked
        // TODO add your handling code here:
        new TaoHoaDon_GUI(this, this.Ma_NV);
        this.setEnabled(false);
    }//GEN-LAST:event_btn_TaoHoaDonMouseClicked

    private void menuItemDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemDangXuatActionPerformed
        // TODO add your handling code here:
        this.dispose();
        this.dangNhap_GUI.setVisible(true);
        this.dangNhap_GUI.setText_passwordNull();
    }//GEN-LAST:event_menuItemDangXuatActionPerformed

    private void menuItemDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemDoiMatKhauActionPerformed
        // TODO add your handling code here:
        new DoiMatKhau_GUI(this, this.Ma_NV);
        this.setEnabled(false);
    }//GEN-LAST:event_menuItemDoiMatKhauActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImageHome;
    private javax.swing.JLabel ImageLogo;
    private javax.swing.JLabel ImageProfile;
    private javax.swing.JButton btn_DanhSachNV;
    private javax.swing.JButton btn_QuanLyHoaDon;
    private javax.swing.JButton btn_QuanLyKhachHang;
    private javax.swing.JButton btn_QuanLySach;
    private javax.swing.JButton btn_TaoHoaDon;
    private javax.swing.JButton btn_ThongTin;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JMenu menuHome;
    private javax.swing.JMenuItem menuItemDangXuat;
    private javax.swing.JMenuItem menuItemDoiMatKhau;
    // End of variables declaration//GEN-END:variables
}
